package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf1010WSoshiki extends Skf1010WSoshikiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.agency_name
	 * @mbg.generated
	 */
	private String agencyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.agency_abbr
	 * @mbg.generated
	 */
	private String agencyAbbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.affiliation1_name
	 * @mbg.generated
	 */
	private String affiliation1Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.affiliation1_abbr
	 * @mbg.generated
	 */
	private String affiliation1Abbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.affiliation2_name
	 * @mbg.generated
	 */
	private String affiliation2Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.affiliation2_abbr
	 * @mbg.generated
	 */
	private String affiliation2Abbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.business_area_cd
	 * @mbg.generated
	 */
	private String businessAreaCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.announce_date
	 * @mbg.generated
	 */
	private String announceDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.key_date
	 * @mbg.generated
	 */
	private String keyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.zip_cd
	 * @mbg.generated
	 */
	private String zipCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.tel
	 * @mbg.generated
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.fax
	 * @mbg.generated
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_w_soshiki.regist_flg
	 * @mbg.generated
	 */
	private String registFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf1010_w_soshiki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.agency_name
	 * @return  the value of skf.skf1010_w_soshiki.agency_name
	 * @mbg.generated
	 */
	public String getAgencyName() {
		return agencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.agency_name
	 * @param agencyName  the value for skf.skf1010_w_soshiki.agency_name
	 * @mbg.generated
	 */
	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.agency_abbr
	 * @return  the value of skf.skf1010_w_soshiki.agency_abbr
	 * @mbg.generated
	 */
	public String getAgencyAbbr() {
		return agencyAbbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.agency_abbr
	 * @param agencyAbbr  the value for skf.skf1010_w_soshiki.agency_abbr
	 * @mbg.generated
	 */
	public void setAgencyAbbr(String agencyAbbr) {
		this.agencyAbbr = agencyAbbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.affiliation1_name
	 * @return  the value of skf.skf1010_w_soshiki.affiliation1_name
	 * @mbg.generated
	 */
	public String getAffiliation1Name() {
		return affiliation1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.affiliation1_name
	 * @param affiliation1Name  the value for skf.skf1010_w_soshiki.affiliation1_name
	 * @mbg.generated
	 */
	public void setAffiliation1Name(String affiliation1Name) {
		this.affiliation1Name = affiliation1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.affiliation1_abbr
	 * @return  the value of skf.skf1010_w_soshiki.affiliation1_abbr
	 * @mbg.generated
	 */
	public String getAffiliation1Abbr() {
		return affiliation1Abbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.affiliation1_abbr
	 * @param affiliation1Abbr  the value for skf.skf1010_w_soshiki.affiliation1_abbr
	 * @mbg.generated
	 */
	public void setAffiliation1Abbr(String affiliation1Abbr) {
		this.affiliation1Abbr = affiliation1Abbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.affiliation2_name
	 * @return  the value of skf.skf1010_w_soshiki.affiliation2_name
	 * @mbg.generated
	 */
	public String getAffiliation2Name() {
		return affiliation2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.affiliation2_name
	 * @param affiliation2Name  the value for skf.skf1010_w_soshiki.affiliation2_name
	 * @mbg.generated
	 */
	public void setAffiliation2Name(String affiliation2Name) {
		this.affiliation2Name = affiliation2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.affiliation2_abbr
	 * @return  the value of skf.skf1010_w_soshiki.affiliation2_abbr
	 * @mbg.generated
	 */
	public String getAffiliation2Abbr() {
		return affiliation2Abbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.affiliation2_abbr
	 * @param affiliation2Abbr  the value for skf.skf1010_w_soshiki.affiliation2_abbr
	 * @mbg.generated
	 */
	public void setAffiliation2Abbr(String affiliation2Abbr) {
		this.affiliation2Abbr = affiliation2Abbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.business_area_cd
	 * @return  the value of skf.skf1010_w_soshiki.business_area_cd
	 * @mbg.generated
	 */
	public String getBusinessAreaCd() {
		return businessAreaCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.business_area_cd
	 * @param businessAreaCd  the value for skf.skf1010_w_soshiki.business_area_cd
	 * @mbg.generated
	 */
	public void setBusinessAreaCd(String businessAreaCd) {
		this.businessAreaCd = businessAreaCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.announce_date
	 * @return  the value of skf.skf1010_w_soshiki.announce_date
	 * @mbg.generated
	 */
	public String getAnnounceDate() {
		return announceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.announce_date
	 * @param announceDate  the value for skf.skf1010_w_soshiki.announce_date
	 * @mbg.generated
	 */
	public void setAnnounceDate(String announceDate) {
		this.announceDate = announceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.key_date
	 * @return  the value of skf.skf1010_w_soshiki.key_date
	 * @mbg.generated
	 */
	public String getKeyDate() {
		return keyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.key_date
	 * @param keyDate  the value for skf.skf1010_w_soshiki.key_date
	 * @mbg.generated
	 */
	public void setKeyDate(String keyDate) {
		this.keyDate = keyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.zip_cd
	 * @return  the value of skf.skf1010_w_soshiki.zip_cd
	 * @mbg.generated
	 */
	public String getZipCd() {
		return zipCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.zip_cd
	 * @param zipCd  the value for skf.skf1010_w_soshiki.zip_cd
	 * @mbg.generated
	 */
	public void setZipCd(String zipCd) {
		this.zipCd = zipCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.address
	 * @return  the value of skf.skf1010_w_soshiki.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.address
	 * @param address  the value for skf.skf1010_w_soshiki.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.tel
	 * @return  the value of skf.skf1010_w_soshiki.tel
	 * @mbg.generated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.tel
	 * @param tel  the value for skf.skf1010_w_soshiki.tel
	 * @mbg.generated
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.fax
	 * @return  the value of skf.skf1010_w_soshiki.fax
	 * @mbg.generated
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.fax
	 * @param fax  the value for skf.skf1010_w_soshiki.fax
	 * @mbg.generated
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_w_soshiki.regist_flg
	 * @return  the value of skf.skf1010_w_soshiki.regist_flg
	 * @mbg.generated
	 */
	public String getRegistFlg() {
		return registFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_w_soshiki.regist_flg
	 * @param registFlg  the value for skf.skf1010_w_soshiki.regist_flg
	 * @mbg.generated
	 */
	public void setRegistFlg(String registFlg) {
		this.registFlg = registFlg;
	}
}