package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf1010MShatakuShainRireki extends Skf1010MShatakuShainRirekiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.agency_cd
	 * @mbg.generated
	 */
	private String agencyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.agency_name
	 * @mbg.generated
	 */
	private String agencyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.affiliation1_cd
	 * @mbg.generated
	 */
	private String affiliation1Cd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.affiliation1_name
	 * @mbg.generated
	 */
	private String affiliation1Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.affiliation2_cd
	 * @mbg.generated
	 */
	private String affiliation2Cd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.affiliation2_name
	 * @mbg.generated
	 */
	private String affiliation2Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.business_area_cd
	 * @mbg.generated
	 */
	private String businessAreaCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.business_area_name
	 * @mbg.generated
	 */
	private String businessAreaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf1010_m_shataku_shain_rireki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.agency_cd
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.agency_cd
	 * @mbg.generated
	 */
	public String getAgencyCd() {
		return agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.agency_cd
	 * @param agencyCd  the value for skf.skf1010_m_shataku_shain_rireki.agency_cd
	 * @mbg.generated
	 */
	public void setAgencyCd(String agencyCd) {
		this.agencyCd = agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.agency_name
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.agency_name
	 * @mbg.generated
	 */
	public String getAgencyName() {
		return agencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.agency_name
	 * @param agencyName  the value for skf.skf1010_m_shataku_shain_rireki.agency_name
	 * @mbg.generated
	 */
	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation1_cd
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.affiliation1_cd
	 * @mbg.generated
	 */
	public String getAffiliation1Cd() {
		return affiliation1Cd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation1_cd
	 * @param affiliation1Cd  the value for skf.skf1010_m_shataku_shain_rireki.affiliation1_cd
	 * @mbg.generated
	 */
	public void setAffiliation1Cd(String affiliation1Cd) {
		this.affiliation1Cd = affiliation1Cd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation1_name
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.affiliation1_name
	 * @mbg.generated
	 */
	public String getAffiliation1Name() {
		return affiliation1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation1_name
	 * @param affiliation1Name  the value for skf.skf1010_m_shataku_shain_rireki.affiliation1_name
	 * @mbg.generated
	 */
	public void setAffiliation1Name(String affiliation1Name) {
		this.affiliation1Name = affiliation1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation2_cd
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.affiliation2_cd
	 * @mbg.generated
	 */
	public String getAffiliation2Cd() {
		return affiliation2Cd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation2_cd
	 * @param affiliation2Cd  the value for skf.skf1010_m_shataku_shain_rireki.affiliation2_cd
	 * @mbg.generated
	 */
	public void setAffiliation2Cd(String affiliation2Cd) {
		this.affiliation2Cd = affiliation2Cd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation2_name
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.affiliation2_name
	 * @mbg.generated
	 */
	public String getAffiliation2Name() {
		return affiliation2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.affiliation2_name
	 * @param affiliation2Name  the value for skf.skf1010_m_shataku_shain_rireki.affiliation2_name
	 * @mbg.generated
	 */
	public void setAffiliation2Name(String affiliation2Name) {
		this.affiliation2Name = affiliation2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.business_area_cd
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.business_area_cd
	 * @mbg.generated
	 */
	public String getBusinessAreaCd() {
		return businessAreaCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.business_area_cd
	 * @param businessAreaCd  the value for skf.skf1010_m_shataku_shain_rireki.business_area_cd
	 * @mbg.generated
	 */
	public void setBusinessAreaCd(String businessAreaCd) {
		this.businessAreaCd = businessAreaCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.business_area_name
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.business_area_name
	 * @mbg.generated
	 */
	public String getBusinessAreaName() {
		return businessAreaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.business_area_name
	 * @param businessAreaName  the value for skf.skf1010_m_shataku_shain_rireki.business_area_name
	 * @mbg.generated
	 */
	public void setBusinessAreaName(String businessAreaName) {
		this.businessAreaName = businessAreaName;
	}
}