package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf1010MBusinessArea extends Skf1010MBusinessAreaKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_business_area.agency_cd
	 * @mbg.generated
	 */
	private String agencyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_business_area.business_area_name
	 * @mbg.generated
	 */
	private String businessAreaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf1010_m_business_area
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_business_area.agency_cd
	 * @return  the value of skf.skf1010_m_business_area.agency_cd
	 * @mbg.generated
	 */
	public String getAgencyCd() {
		return agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_business_area.agency_cd
	 * @param agencyCd  the value for skf.skf1010_m_business_area.agency_cd
	 * @mbg.generated
	 */
	public void setAgencyCd(String agencyCd) {
		this.agencyCd = agencyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_business_area.business_area_name
	 * @return  the value of skf.skf1010_m_business_area.business_area_name
	 * @mbg.generated
	 */
	public String getBusinessAreaName() {
		return businessAreaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_business_area.business_area_name
	 * @param businessAreaName  the value for skf.skf1010_m_business_area.business_area_name
	 * @mbg.generated
	 */
	public void setBusinessAreaName(String businessAreaName) {
		this.businessAreaName = businessAreaName;
	}
}