package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf1010MShatakuShainRirekiKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.company_cd
	 * @mbg.generated
	 */
	private String companyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.year_month
	 * @mbg.generated
	 */
	private String yearMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_shataku_shain_rireki.beginning_end_kbn
	 * @mbg.generated
	 */
	private String beginningEndKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf1010_m_shataku_shain_rireki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.company_cd
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.company_cd
	 * @mbg.generated
	 */
	public String getCompanyCd() {
		return companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.company_cd
	 * @param companyCd  the value for skf.skf1010_m_shataku_shain_rireki.company_cd
	 * @mbg.generated
	 */
	public void setCompanyCd(String companyCd) {
		this.companyCd = companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.shain_no
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.shain_no
	 * @param shainNo  the value for skf.skf1010_m_shataku_shain_rireki.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.year_month
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.year_month
	 * @mbg.generated
	 */
	public String getYearMonth() {
		return yearMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.year_month
	 * @param yearMonth  the value for skf.skf1010_m_shataku_shain_rireki.year_month
	 * @mbg.generated
	 */
	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_shataku_shain_rireki.beginning_end_kbn
	 * @return  the value of skf.skf1010_m_shataku_shain_rireki.beginning_end_kbn
	 * @mbg.generated
	 */
	public String getBeginningEndKbn() {
		return beginningEndKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_shataku_shain_rireki.beginning_end_kbn
	 * @param beginningEndKbn  the value for skf.skf1010_m_shataku_shain_rireki.beginning_end_kbn
	 * @mbg.generated
	 */
	public void setBeginningEndKbn(String beginningEndKbn) {
		this.beginningEndKbn = beginningEndKbn;
	}
}