package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf1010MTokyu extends Skf1010MTokyuKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_tokyu.tokyu_name
	 * @mbg.generated
	 */
	private String tokyuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_m_tokyu.invalid_flg
	 * @mbg.generated
	 */
	private String invalidFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf1010_m_tokyu
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_tokyu.tokyu_name
	 * @return  the value of skf.skf1010_m_tokyu.tokyu_name
	 * @mbg.generated
	 */
	public String getTokyuName() {
		return tokyuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_tokyu.tokyu_name
	 * @param tokyuName  the value for skf.skf1010_m_tokyu.tokyu_name
	 * @mbg.generated
	 */
	public void setTokyuName(String tokyuName) {
		this.tokyuName = tokyuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_m_tokyu.invalid_flg
	 * @return  the value of skf.skf1010_m_tokyu.invalid_flg
	 * @mbg.generated
	 */
	public String getInvalidFlg() {
		return invalidFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_m_tokyu.invalid_flg
	 * @param invalidFlg  the value for skf.skf1010_m_tokyu.invalid_flg
	 * @mbg.generated
	 */
	public void setInvalidFlg(String invalidFlg) {
		this.invalidFlg = invalidFlg;
	}
}