package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf1010TInformationKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_t_information.company_cd
	 * @mbg.generated
	 */
	private String companyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf1010_t_information.open_date
	 * @mbg.generated
	 */
	private String openDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf1010_t_information
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_t_information.company_cd
	 * @return  the value of skf.skf1010_t_information.company_cd
	 * @mbg.generated
	 */
	public String getCompanyCd() {
		return companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_t_information.company_cd
	 * @param companyCd  the value for skf.skf1010_t_information.company_cd
	 * @mbg.generated
	 */
	public void setCompanyCd(String companyCd) {
		this.companyCd = companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf1010_t_information.open_date
	 * @return  the value of skf.skf1010_t_information.open_date
	 * @mbg.generated
	 */
	public String getOpenDate() {
		return openDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf1010_t_information.open_date
	 * @param openDate  the value for skf.skf1010_t_information.open_date
	 * @mbg.generated
	 */
	public void setOpenDate(String openDate) {
		this.openDate = openDate;
	}
}