package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2030TBihinKiboShinsei extends Skf2030TBihinKiboShinseiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.nyukyo_appl_no
	 * @mbg.generated
	 */
	private String nyukyoApplNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.appl_date
	 * @mbg.generated
	 */
	private String applDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.agency
	 * @mbg.generated
	 */
	private String agency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.affiliation1
	 * @mbg.generated
	 */
	private String affiliation1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.affiliation2
	 * @mbg.generated
	 */
	private String affiliation2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.tel
	 * @mbg.generated
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.tokyu
	 * @mbg.generated
	 */
	private String tokyu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.gender
	 * @mbg.generated
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.shataku_no
	 * @mbg.generated
	 */
	private Long shatakuNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.room_kanri_no
	 * @mbg.generated
	 */
	private Long roomKanriNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_name
	 * @mbg.generated
	 */
	private String nowShatakuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_no
	 * @mbg.generated
	 */
	private String nowShatakuNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_kikaku
	 * @mbg.generated
	 */
	private String nowShatakuKikaku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_menseki
	 * @mbg.generated
	 */
	private String nowShatakuMenseki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.renraku_saki
	 * @mbg.generated
	 */
	private String renrakuSaki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_name
	 * @mbg.generated
	 */
	private String ukeireDairiName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_apoint
	 * @mbg.generated
	 */
	private String ukeireDairiApoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.session_day
	 * @mbg.generated
	 */
	private String sessionDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.session_time
	 * @mbg.generated
	 */
	private String sessionTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2030_t_bihin_kibo_shinsei.completion_day
	 * @mbg.generated
	 */
	private String completionDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2030_t_bihin_kibo_shinsei
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.nyukyo_appl_no
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.nyukyo_appl_no
	 * @mbg.generated
	 */
	public String getNyukyoApplNo() {
		return nyukyoApplNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.nyukyo_appl_no
	 * @param nyukyoApplNo  the value for skf.skf2030_t_bihin_kibo_shinsei.nyukyo_appl_no
	 * @mbg.generated
	 */
	public void setNyukyoApplNo(String nyukyoApplNo) {
		this.nyukyoApplNo = nyukyoApplNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.appl_date
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.appl_date
	 * @mbg.generated
	 */
	public String getApplDate() {
		return applDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.appl_date
	 * @param applDate  the value for skf.skf2030_t_bihin_kibo_shinsei.appl_date
	 * @mbg.generated
	 */
	public void setApplDate(String applDate) {
		this.applDate = applDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.agency
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.agency
	 * @mbg.generated
	 */
	public String getAgency() {
		return agency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.agency
	 * @param agency  the value for skf.skf2030_t_bihin_kibo_shinsei.agency
	 * @mbg.generated
	 */
	public void setAgency(String agency) {
		this.agency = agency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.affiliation1
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.affiliation1
	 * @mbg.generated
	 */
	public String getAffiliation1() {
		return affiliation1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.affiliation1
	 * @param affiliation1  the value for skf.skf2030_t_bihin_kibo_shinsei.affiliation1
	 * @mbg.generated
	 */
	public void setAffiliation1(String affiliation1) {
		this.affiliation1 = affiliation1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.affiliation2
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.affiliation2
	 * @mbg.generated
	 */
	public String getAffiliation2() {
		return affiliation2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.affiliation2
	 * @param affiliation2  the value for skf.skf2030_t_bihin_kibo_shinsei.affiliation2
	 * @mbg.generated
	 */
	public void setAffiliation2(String affiliation2) {
		this.affiliation2 = affiliation2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.tel
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.tel
	 * @mbg.generated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.tel
	 * @param tel  the value for skf.skf2030_t_bihin_kibo_shinsei.tel
	 * @mbg.generated
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.shain_no
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.shain_no
	 * @param shainNo  the value for skf.skf2030_t_bihin_kibo_shinsei.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.name
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.name
	 * @param name  the value for skf.skf2030_t_bihin_kibo_shinsei.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.tokyu
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.tokyu
	 * @mbg.generated
	 */
	public String getTokyu() {
		return tokyu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.tokyu
	 * @param tokyu  the value for skf.skf2030_t_bihin_kibo_shinsei.tokyu
	 * @mbg.generated
	 */
	public void setTokyu(String tokyu) {
		this.tokyu = tokyu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.gender
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.gender
	 * @mbg.generated
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.gender
	 * @param gender  the value for skf.skf2030_t_bihin_kibo_shinsei.gender
	 * @mbg.generated
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.shataku_no
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.shataku_no
	 * @mbg.generated
	 */
	public Long getShatakuNo() {
		return shatakuNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.shataku_no
	 * @param shatakuNo  the value for skf.skf2030_t_bihin_kibo_shinsei.shataku_no
	 * @mbg.generated
	 */
	public void setShatakuNo(Long shatakuNo) {
		this.shatakuNo = shatakuNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.room_kanri_no
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.room_kanri_no
	 * @mbg.generated
	 */
	public Long getRoomKanriNo() {
		return roomKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.room_kanri_no
	 * @param roomKanriNo  the value for skf.skf2030_t_bihin_kibo_shinsei.room_kanri_no
	 * @mbg.generated
	 */
	public void setRoomKanriNo(Long roomKanriNo) {
		this.roomKanriNo = roomKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_name
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.now_shataku_name
	 * @mbg.generated
	 */
	public String getNowShatakuName() {
		return nowShatakuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_name
	 * @param nowShatakuName  the value for skf.skf2030_t_bihin_kibo_shinsei.now_shataku_name
	 * @mbg.generated
	 */
	public void setNowShatakuName(String nowShatakuName) {
		this.nowShatakuName = nowShatakuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_no
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.now_shataku_no
	 * @mbg.generated
	 */
	public String getNowShatakuNo() {
		return nowShatakuNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_no
	 * @param nowShatakuNo  the value for skf.skf2030_t_bihin_kibo_shinsei.now_shataku_no
	 * @mbg.generated
	 */
	public void setNowShatakuNo(String nowShatakuNo) {
		this.nowShatakuNo = nowShatakuNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_kikaku
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.now_shataku_kikaku
	 * @mbg.generated
	 */
	public String getNowShatakuKikaku() {
		return nowShatakuKikaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_kikaku
	 * @param nowShatakuKikaku  the value for skf.skf2030_t_bihin_kibo_shinsei.now_shataku_kikaku
	 * @mbg.generated
	 */
	public void setNowShatakuKikaku(String nowShatakuKikaku) {
		this.nowShatakuKikaku = nowShatakuKikaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_menseki
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.now_shataku_menseki
	 * @mbg.generated
	 */
	public String getNowShatakuMenseki() {
		return nowShatakuMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.now_shataku_menseki
	 * @param nowShatakuMenseki  the value for skf.skf2030_t_bihin_kibo_shinsei.now_shataku_menseki
	 * @mbg.generated
	 */
	public void setNowShatakuMenseki(String nowShatakuMenseki) {
		this.nowShatakuMenseki = nowShatakuMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.renraku_saki
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.renraku_saki
	 * @mbg.generated
	 */
	public String getRenrakuSaki() {
		return renrakuSaki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.renraku_saki
	 * @param renrakuSaki  the value for skf.skf2030_t_bihin_kibo_shinsei.renraku_saki
	 * @mbg.generated
	 */
	public void setRenrakuSaki(String renrakuSaki) {
		this.renrakuSaki = renrakuSaki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_name
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_name
	 * @mbg.generated
	 */
	public String getUkeireDairiName() {
		return ukeireDairiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_name
	 * @param ukeireDairiName  the value for skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_name
	 * @mbg.generated
	 */
	public void setUkeireDairiName(String ukeireDairiName) {
		this.ukeireDairiName = ukeireDairiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_apoint
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_apoint
	 * @mbg.generated
	 */
	public String getUkeireDairiApoint() {
		return ukeireDairiApoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_apoint
	 * @param ukeireDairiApoint  the value for skf.skf2030_t_bihin_kibo_shinsei.ukeire_dairi_apoint
	 * @mbg.generated
	 */
	public void setUkeireDairiApoint(String ukeireDairiApoint) {
		this.ukeireDairiApoint = ukeireDairiApoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.session_day
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.session_day
	 * @mbg.generated
	 */
	public String getSessionDay() {
		return sessionDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.session_day
	 * @param sessionDay  the value for skf.skf2030_t_bihin_kibo_shinsei.session_day
	 * @mbg.generated
	 */
	public void setSessionDay(String sessionDay) {
		this.sessionDay = sessionDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.session_time
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.session_time
	 * @mbg.generated
	 */
	public String getSessionTime() {
		return sessionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.session_time
	 * @param sessionTime  the value for skf.skf2030_t_bihin_kibo_shinsei.session_time
	 * @mbg.generated
	 */
	public void setSessionTime(String sessionTime) {
		this.sessionTime = sessionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2030_t_bihin_kibo_shinsei.completion_day
	 * @return  the value of skf.skf2030_t_bihin_kibo_shinsei.completion_day
	 * @mbg.generated
	 */
	public String getCompletionDay() {
		return completionDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2030_t_bihin_kibo_shinsei.completion_day
	 * @param completionDay  the value for skf.skf2030_t_bihin_kibo_shinsei.completion_day
	 * @mbg.generated
	 */
	public void setCompletionDay(String completionDay) {
		this.completionDay = completionDay;
	}
}