package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2100MMobileRouter extends Skf2100MMobileRouterKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.tel
	 * @mbg.generated
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.iccid
	 * @mbg.generated
	 */
	private String iccid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.imei
	 * @mbg.generated
	 */
	private String imei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.ssid_a
	 * @mbg.generated
	 */
	private String ssidA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.wpa_key
	 * @mbg.generated
	 */
	private String wpaKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_arrival_date
	 * @mbg.generated
	 */
	private String routerArrivalDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_contract_start_date
	 * @mbg.generated
	 */
	private String routerContractStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_contract_end_date
	 * @mbg.generated
	 */
	private String routerContractEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_contract_kbn
	 * @mbg.generated
	 */
	private String routerContractKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_lending_judgment
	 * @mbg.generated
	 */
	private String routerLendingJudgment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.fault_flag
	 * @mbg.generated
	 */
	private String faultFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.biko
	 * @mbg.generated
	 */
	private String biko;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_name_1
	 * @mbg.generated
	 */
	private String routerSupplementName1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_name_2
	 * @mbg.generated
	 */
	private String routerSupplementName2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_name_3
	 * @mbg.generated
	 */
	private String routerSupplementName3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_size_1
	 * @mbg.generated
	 */
	private String routerSupplementSize1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_size_2
	 * @mbg.generated
	 */
	private String routerSupplementSize2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_size_3
	 * @mbg.generated
	 */
	private String routerSupplementSize3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2100_m_mobile_router
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.tel
	 * @return  the value of skf.skf2100_m_mobile_router.tel
	 * @mbg.generated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.tel
	 * @param tel  the value for skf.skf2100_m_mobile_router.tel
	 * @mbg.generated
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.iccid
	 * @return  the value of skf.skf2100_m_mobile_router.iccid
	 * @mbg.generated
	 */
	public String getIccid() {
		return iccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.iccid
	 * @param iccid  the value for skf.skf2100_m_mobile_router.iccid
	 * @mbg.generated
	 */
	public void setIccid(String iccid) {
		this.iccid = iccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.imei
	 * @return  the value of skf.skf2100_m_mobile_router.imei
	 * @mbg.generated
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.imei
	 * @param imei  the value for skf.skf2100_m_mobile_router.imei
	 * @mbg.generated
	 */
	public void setImei(String imei) {
		this.imei = imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.ssid_a
	 * @return  the value of skf.skf2100_m_mobile_router.ssid_a
	 * @mbg.generated
	 */
	public String getSsidA() {
		return ssidA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.ssid_a
	 * @param ssidA  the value for skf.skf2100_m_mobile_router.ssid_a
	 * @mbg.generated
	 */
	public void setSsidA(String ssidA) {
		this.ssidA = ssidA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.wpa_key
	 * @return  the value of skf.skf2100_m_mobile_router.wpa_key
	 * @mbg.generated
	 */
	public String getWpaKey() {
		return wpaKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.wpa_key
	 * @param wpaKey  the value for skf.skf2100_m_mobile_router.wpa_key
	 * @mbg.generated
	 */
	public void setWpaKey(String wpaKey) {
		this.wpaKey = wpaKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_arrival_date
	 * @return  the value of skf.skf2100_m_mobile_router.router_arrival_date
	 * @mbg.generated
	 */
	public String getRouterArrivalDate() {
		return routerArrivalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_arrival_date
	 * @param routerArrivalDate  the value for skf.skf2100_m_mobile_router.router_arrival_date
	 * @mbg.generated
	 */
	public void setRouterArrivalDate(String routerArrivalDate) {
		this.routerArrivalDate = routerArrivalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_contract_start_date
	 * @return  the value of skf.skf2100_m_mobile_router.router_contract_start_date
	 * @mbg.generated
	 */
	public String getRouterContractStartDate() {
		return routerContractStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_contract_start_date
	 * @param routerContractStartDate  the value for skf.skf2100_m_mobile_router.router_contract_start_date
	 * @mbg.generated
	 */
	public void setRouterContractStartDate(String routerContractStartDate) {
		this.routerContractStartDate = routerContractStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_contract_end_date
	 * @return  the value of skf.skf2100_m_mobile_router.router_contract_end_date
	 * @mbg.generated
	 */
	public String getRouterContractEndDate() {
		return routerContractEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_contract_end_date
	 * @param routerContractEndDate  the value for skf.skf2100_m_mobile_router.router_contract_end_date
	 * @mbg.generated
	 */
	public void setRouterContractEndDate(String routerContractEndDate) {
		this.routerContractEndDate = routerContractEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_contract_kbn
	 * @return  the value of skf.skf2100_m_mobile_router.router_contract_kbn
	 * @mbg.generated
	 */
	public String getRouterContractKbn() {
		return routerContractKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_contract_kbn
	 * @param routerContractKbn  the value for skf.skf2100_m_mobile_router.router_contract_kbn
	 * @mbg.generated
	 */
	public void setRouterContractKbn(String routerContractKbn) {
		this.routerContractKbn = routerContractKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_lending_judgment
	 * @return  the value of skf.skf2100_m_mobile_router.router_lending_judgment
	 * @mbg.generated
	 */
	public String getRouterLendingJudgment() {
		return routerLendingJudgment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_lending_judgment
	 * @param routerLendingJudgment  the value for skf.skf2100_m_mobile_router.router_lending_judgment
	 * @mbg.generated
	 */
	public void setRouterLendingJudgment(String routerLendingJudgment) {
		this.routerLendingJudgment = routerLendingJudgment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.fault_flag
	 * @return  the value of skf.skf2100_m_mobile_router.fault_flag
	 * @mbg.generated
	 */
	public String getFaultFlag() {
		return faultFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.fault_flag
	 * @param faultFlag  the value for skf.skf2100_m_mobile_router.fault_flag
	 * @mbg.generated
	 */
	public void setFaultFlag(String faultFlag) {
		this.faultFlag = faultFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.biko
	 * @return  the value of skf.skf2100_m_mobile_router.biko
	 * @mbg.generated
	 */
	public String getBiko() {
		return biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.biko
	 * @param biko  the value for skf.skf2100_m_mobile_router.biko
	 * @mbg.generated
	 */
	public void setBiko(String biko) {
		this.biko = biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_name_1
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_name_1
	 * @mbg.generated
	 */
	public String getRouterSupplementName1() {
		return routerSupplementName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_name_1
	 * @param routerSupplementName1  the value for skf.skf2100_m_mobile_router.router_supplement_name_1
	 * @mbg.generated
	 */
	public void setRouterSupplementName1(String routerSupplementName1) {
		this.routerSupplementName1 = routerSupplementName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_name_2
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_name_2
	 * @mbg.generated
	 */
	public String getRouterSupplementName2() {
		return routerSupplementName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_name_2
	 * @param routerSupplementName2  the value for skf.skf2100_m_mobile_router.router_supplement_name_2
	 * @mbg.generated
	 */
	public void setRouterSupplementName2(String routerSupplementName2) {
		this.routerSupplementName2 = routerSupplementName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_name_3
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_name_3
	 * @mbg.generated
	 */
	public String getRouterSupplementName3() {
		return routerSupplementName3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_name_3
	 * @param routerSupplementName3  the value for skf.skf2100_m_mobile_router.router_supplement_name_3
	 * @mbg.generated
	 */
	public void setRouterSupplementName3(String routerSupplementName3) {
		this.routerSupplementName3 = routerSupplementName3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_size_1
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_size_1
	 * @mbg.generated
	 */
	public String getRouterSupplementSize1() {
		return routerSupplementSize1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_size_1
	 * @param routerSupplementSize1  the value for skf.skf2100_m_mobile_router.router_supplement_size_1
	 * @mbg.generated
	 */
	public void setRouterSupplementSize1(String routerSupplementSize1) {
		this.routerSupplementSize1 = routerSupplementSize1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_size_2
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_size_2
	 * @mbg.generated
	 */
	public String getRouterSupplementSize2() {
		return routerSupplementSize2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_size_2
	 * @param routerSupplementSize2  the value for skf.skf2100_m_mobile_router.router_supplement_size_2
	 * @mbg.generated
	 */
	public void setRouterSupplementSize2(String routerSupplementSize2) {
		this.routerSupplementSize2 = routerSupplementSize2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_size_3
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_size_3
	 * @mbg.generated
	 */
	public String getRouterSupplementSize3() {
		return routerSupplementSize3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_size_3
	 * @param routerSupplementSize3  the value for skf.skf2100_m_mobile_router.router_supplement_size_3
	 * @mbg.generated
	 */
	public void setRouterSupplementSize3(String routerSupplementSize3) {
		this.routerSupplementSize3 = routerSupplementSize3;
	}
}