package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2060TKariageTeijiDetail extends Skf2060TKariageTeijiDetailKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_teiji_detail.shataku_name
	 * @mbg.generated
	 */
	private String shatakuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_teiji_detail.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_teiji_detail.money
	 * @mbg.generated
	 */
	private String money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_teiji_detail.appl_check_flg
	 * @mbg.generated
	 */
	private String applCheckFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_teiji_detail.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2060_t_kariage_teiji_detail
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_teiji_detail.shataku_name
	 * @return  the value of skf.skf2060_t_kariage_teiji_detail.shataku_name
	 * @mbg.generated
	 */
	public String getShatakuName() {
		return shatakuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_teiji_detail.shataku_name
	 * @param shatakuName  the value for skf.skf2060_t_kariage_teiji_detail.shataku_name
	 * @mbg.generated
	 */
	public void setShatakuName(String shatakuName) {
		this.shatakuName = shatakuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_teiji_detail.address
	 * @return  the value of skf.skf2060_t_kariage_teiji_detail.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_teiji_detail.address
	 * @param address  the value for skf.skf2060_t_kariage_teiji_detail.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_teiji_detail.money
	 * @return  the value of skf.skf2060_t_kariage_teiji_detail.money
	 * @mbg.generated
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_teiji_detail.money
	 * @param money  the value for skf.skf2060_t_kariage_teiji_detail.money
	 * @mbg.generated
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_teiji_detail.appl_check_flg
	 * @return  the value of skf.skf2060_t_kariage_teiji_detail.appl_check_flg
	 * @mbg.generated
	 */
	public String getApplCheckFlg() {
		return applCheckFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_teiji_detail.appl_check_flg
	 * @param applCheckFlg  the value for skf.skf2060_t_kariage_teiji_detail.appl_check_flg
	 * @mbg.generated
	 */
	public void setApplCheckFlg(String applCheckFlg) {
		this.applCheckFlg = applCheckFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_teiji_detail.shain_no
	 * @return  the value of skf.skf2060_t_kariage_teiji_detail.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_teiji_detail.shain_no
	 * @param shainNo  the value for skf.skf2060_t_kariage_teiji_detail.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}
}