package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf2010MWorkflowLevelKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_m_workflow_level.company_cd
	 * @mbg.generated
	 */
	private String companyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_m_workflow_level.wf_id
	 * @mbg.generated
	 */
	private String wfId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_m_workflow_level.wf_level
	 * @mbg.generated
	 */
	private String wfLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2010_m_workflow_level
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_m_workflow_level.company_cd
	 * @return  the value of skf.skf2010_m_workflow_level.company_cd
	 * @mbg.generated
	 */
	public String getCompanyCd() {
		return companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_m_workflow_level.company_cd
	 * @param companyCd  the value for skf.skf2010_m_workflow_level.company_cd
	 * @mbg.generated
	 */
	public void setCompanyCd(String companyCd) {
		this.companyCd = companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_m_workflow_level.wf_id
	 * @return  the value of skf.skf2010_m_workflow_level.wf_id
	 * @mbg.generated
	 */
	public String getWfId() {
		return wfId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_m_workflow_level.wf_id
	 * @param wfId  the value for skf.skf2010_m_workflow_level.wf_id
	 * @mbg.generated
	 */
	public void setWfId(String wfId) {
		this.wfId = wfId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_m_workflow_level.wf_level
	 * @return  the value of skf.skf2010_m_workflow_level.wf_level
	 * @mbg.generated
	 */
	public String getWfLevel() {
		return wfLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_m_workflow_level.wf_level
	 * @param wfLevel  the value for skf.skf2010_m_workflow_level.wf_level
	 * @mbg.generated
	 */
	public void setWfLevel(String wfLevel) {
		this.wfLevel = wfLevel;
	}
}