package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2010MApplicationCtgry extends Skf2010MApplicationCtgryKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_m_application_ctgry.appl_ctgry_name
	 * @mbg.generated
	 */
	private String applCtgryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_m_application_ctgry.view_order
	 * @mbg.generated
	 */
	private Short viewOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2010_m_application_ctgry
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_m_application_ctgry.appl_ctgry_name
	 * @return  the value of skf.skf2010_m_application_ctgry.appl_ctgry_name
	 * @mbg.generated
	 */
	public String getApplCtgryName() {
		return applCtgryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_m_application_ctgry.appl_ctgry_name
	 * @param applCtgryName  the value for skf.skf2010_m_application_ctgry.appl_ctgry_name
	 * @mbg.generated
	 */
	public void setApplCtgryName(String applCtgryName) {
		this.applCtgryName = applCtgryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_m_application_ctgry.view_order
	 * @return  the value of skf.skf2010_m_application_ctgry.view_order
	 * @mbg.generated
	 */
	public Short getViewOrder() {
		return viewOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_m_application_ctgry.view_order
	 * @param viewOrder  the value for skf.skf2010_m_application_ctgry.view_order
	 * @mbg.generated
	 */
	public void setViewOrder(Short viewOrder) {
		this.viewOrder = viewOrder;
	}
}