package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2100TMobileRouterKiboShinsei extends Skf2100TMobileRouterKiboShinseiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.appl_date
	 * @mbg.generated
	 */
	private String applDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.agency
	 * @mbg.generated
	 */
	private String agency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.affiliation1
	 * @mbg.generated
	 */
	private String affiliation1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.affiliation2
	 * @mbg.generated
	 */
	private String affiliation2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.tel
	 * @mbg.generated
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.mailaddress
	 * @mbg.generated
	 */
	private String mailaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.use_start_hope_day
	 * @mbg.generated
	 */
	private String useStartHopeDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.original_company_cd
	 * @mbg.generated
	 */
	private String originalCompanyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.pay_company_cd
	 * @mbg.generated
	 */
	private String payCompanyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.mobile_router_no
	 * @mbg.generated
	 */
	private Long mobileRouterNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.iccid
	 * @mbg.generated
	 */
	private String iccid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.imei
	 * @mbg.generated
	 */
	private String imei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.shipping_date
	 * @mbg.generated
	 */
	private String shippingDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.received_date
	 * @mbg.generated
	 */
	private String receivedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.body_receipt_check_flag
	 * @mbg.generated
	 */
	private String bodyReceiptCheckFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.handbook_receipt_check_flag
	 * @mbg.generated
	 */
	private String handbookReceiptCheckFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_kibo_shinsei.materials_received_check_flag
	 * @mbg.generated
	 */
	private String materialsReceivedCheckFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2100_t_mobile_router_kibo_shinsei
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.appl_date
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.appl_date
	 * @mbg.generated
	 */
	public String getApplDate() {
		return applDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.appl_date
	 * @param applDate  the value for skf.skf2100_t_mobile_router_kibo_shinsei.appl_date
	 * @mbg.generated
	 */
	public void setApplDate(String applDate) {
		this.applDate = applDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.shain_no
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.shain_no
	 * @param shainNo  the value for skf.skf2100_t_mobile_router_kibo_shinsei.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.name
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.name
	 * @param name  the value for skf.skf2100_t_mobile_router_kibo_shinsei.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.agency
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.agency
	 * @mbg.generated
	 */
	public String getAgency() {
		return agency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.agency
	 * @param agency  the value for skf.skf2100_t_mobile_router_kibo_shinsei.agency
	 * @mbg.generated
	 */
	public void setAgency(String agency) {
		this.agency = agency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.affiliation1
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.affiliation1
	 * @mbg.generated
	 */
	public String getAffiliation1() {
		return affiliation1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.affiliation1
	 * @param affiliation1  the value for skf.skf2100_t_mobile_router_kibo_shinsei.affiliation1
	 * @mbg.generated
	 */
	public void setAffiliation1(String affiliation1) {
		this.affiliation1 = affiliation1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.affiliation2
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.affiliation2
	 * @mbg.generated
	 */
	public String getAffiliation2() {
		return affiliation2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.affiliation2
	 * @param affiliation2  the value for skf.skf2100_t_mobile_router_kibo_shinsei.affiliation2
	 * @mbg.generated
	 */
	public void setAffiliation2(String affiliation2) {
		this.affiliation2 = affiliation2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.tel
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.tel
	 * @mbg.generated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.tel
	 * @param tel  the value for skf.skf2100_t_mobile_router_kibo_shinsei.tel
	 * @mbg.generated
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.mailaddress
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.mailaddress
	 * @mbg.generated
	 */
	public String getMailaddress() {
		return mailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.mailaddress
	 * @param mailaddress  the value for skf.skf2100_t_mobile_router_kibo_shinsei.mailaddress
	 * @mbg.generated
	 */
	public void setMailaddress(String mailaddress) {
		this.mailaddress = mailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.use_start_hope_day
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.use_start_hope_day
	 * @mbg.generated
	 */
	public String getUseStartHopeDay() {
		return useStartHopeDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.use_start_hope_day
	 * @param useStartHopeDay  the value for skf.skf2100_t_mobile_router_kibo_shinsei.use_start_hope_day
	 * @mbg.generated
	 */
	public void setUseStartHopeDay(String useStartHopeDay) {
		this.useStartHopeDay = useStartHopeDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.original_company_cd
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.original_company_cd
	 * @mbg.generated
	 */
	public String getOriginalCompanyCd() {
		return originalCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.original_company_cd
	 * @param originalCompanyCd  the value for skf.skf2100_t_mobile_router_kibo_shinsei.original_company_cd
	 * @mbg.generated
	 */
	public void setOriginalCompanyCd(String originalCompanyCd) {
		this.originalCompanyCd = originalCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.pay_company_cd
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.pay_company_cd
	 * @mbg.generated
	 */
	public String getPayCompanyCd() {
		return payCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.pay_company_cd
	 * @param payCompanyCd  the value for skf.skf2100_t_mobile_router_kibo_shinsei.pay_company_cd
	 * @mbg.generated
	 */
	public void setPayCompanyCd(String payCompanyCd) {
		this.payCompanyCd = payCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.mobile_router_no
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.mobile_router_no
	 * @mbg.generated
	 */
	public Long getMobileRouterNo() {
		return mobileRouterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.mobile_router_no
	 * @param mobileRouterNo  the value for skf.skf2100_t_mobile_router_kibo_shinsei.mobile_router_no
	 * @mbg.generated
	 */
	public void setMobileRouterNo(Long mobileRouterNo) {
		this.mobileRouterNo = mobileRouterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.iccid
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.iccid
	 * @mbg.generated
	 */
	public String getIccid() {
		return iccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.iccid
	 * @param iccid  the value for skf.skf2100_t_mobile_router_kibo_shinsei.iccid
	 * @mbg.generated
	 */
	public void setIccid(String iccid) {
		this.iccid = iccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.imei
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.imei
	 * @mbg.generated
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.imei
	 * @param imei  the value for skf.skf2100_t_mobile_router_kibo_shinsei.imei
	 * @mbg.generated
	 */
	public void setImei(String imei) {
		this.imei = imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.shipping_date
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.shipping_date
	 * @mbg.generated
	 */
	public String getShippingDate() {
		return shippingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.shipping_date
	 * @param shippingDate  the value for skf.skf2100_t_mobile_router_kibo_shinsei.shipping_date
	 * @mbg.generated
	 */
	public void setShippingDate(String shippingDate) {
		this.shippingDate = shippingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.received_date
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.received_date
	 * @mbg.generated
	 */
	public String getReceivedDate() {
		return receivedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.received_date
	 * @param receivedDate  the value for skf.skf2100_t_mobile_router_kibo_shinsei.received_date
	 * @mbg.generated
	 */
	public void setReceivedDate(String receivedDate) {
		this.receivedDate = receivedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.body_receipt_check_flag
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.body_receipt_check_flag
	 * @mbg.generated
	 */
	public String getBodyReceiptCheckFlag() {
		return bodyReceiptCheckFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.body_receipt_check_flag
	 * @param bodyReceiptCheckFlag  the value for skf.skf2100_t_mobile_router_kibo_shinsei.body_receipt_check_flag
	 * @mbg.generated
	 */
	public void setBodyReceiptCheckFlag(String bodyReceiptCheckFlag) {
		this.bodyReceiptCheckFlag = bodyReceiptCheckFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.handbook_receipt_check_flag
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.handbook_receipt_check_flag
	 * @mbg.generated
	 */
	public String getHandbookReceiptCheckFlag() {
		return handbookReceiptCheckFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.handbook_receipt_check_flag
	 * @param handbookReceiptCheckFlag  the value for skf.skf2100_t_mobile_router_kibo_shinsei.handbook_receipt_check_flag
	 * @mbg.generated
	 */
	public void setHandbookReceiptCheckFlag(String handbookReceiptCheckFlag) {
		this.handbookReceiptCheckFlag = handbookReceiptCheckFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.materials_received_check_flag
	 * @return  the value of skf.skf2100_t_mobile_router_kibo_shinsei.materials_received_check_flag
	 * @mbg.generated
	 */
	public String getMaterialsReceivedCheckFlag() {
		return materialsReceivedCheckFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_kibo_shinsei.materials_received_check_flag
	 * @param materialsReceivedCheckFlag  the value for skf.skf2100_t_mobile_router_kibo_shinsei.materials_received_check_flag
	 * @mbg.generated
	 */
	public void setMaterialsReceivedCheckFlag(String materialsReceivedCheckFlag) {
		this.materialsReceivedCheckFlag = materialsReceivedCheckFlag;
	}
}