package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2100TMobileRouterRentalRireki extends Skf2100TMobileRouterRentalRirekiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_rental_rireki.mobile_router_genbutu_goukei
	 * @mbg.generated
	 */
	private Integer mobileRouterGenbutuGoukei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_rental_rireki.mobile_router_genbutu_goukei
	 * @return  the value of skf.skf2100_t_mobile_router_rental_rireki.mobile_router_genbutu_goukei
	 * @mbg.generated
	 */
	public Integer getMobileRouterGenbutuGoukei() {
		return mobileRouterGenbutuGoukei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_rental_rireki.mobile_router_genbutu_goukei
	 * @param mobileRouterGenbutuGoukei  the value for skf.skf2100_t_mobile_router_rental_rireki.mobile_router_genbutu_goukei
	 * @mbg.generated
	 */
	public void setMobileRouterGenbutuGoukei(Integer mobileRouterGenbutuGoukei) {
		this.mobileRouterGenbutuGoukei = mobileRouterGenbutuGoukei;
	}
}