package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2100MMobileRouterWithBLOBs extends Skf2100MMobileRouter implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_file_1
	 * @mbg.generated
	 */
	private byte[] routerSupplementFile1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_file_2
	 * @mbg.generated
	 */
	private byte[] routerSupplementFile2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_m_mobile_router.router_supplement_file_3
	 * @mbg.generated
	 */
	private byte[] routerSupplementFile3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2100_m_mobile_router
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_file_1
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_file_1
	 * @mbg.generated
	 */
	public byte[] getRouterSupplementFile1() {
		return routerSupplementFile1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_file_1
	 * @param routerSupplementFile1  the value for skf.skf2100_m_mobile_router.router_supplement_file_1
	 * @mbg.generated
	 */
	public void setRouterSupplementFile1(byte[] routerSupplementFile1) {
		this.routerSupplementFile1 = routerSupplementFile1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_file_2
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_file_2
	 * @mbg.generated
	 */
	public byte[] getRouterSupplementFile2() {
		return routerSupplementFile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_file_2
	 * @param routerSupplementFile2  the value for skf.skf2100_m_mobile_router.router_supplement_file_2
	 * @mbg.generated
	 */
	public void setRouterSupplementFile2(byte[] routerSupplementFile2) {
		this.routerSupplementFile2 = routerSupplementFile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_m_mobile_router.router_supplement_file_3
	 * @return  the value of skf.skf2100_m_mobile_router.router_supplement_file_3
	 * @mbg.generated
	 */
	public byte[] getRouterSupplementFile3() {
		return routerSupplementFile3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_m_mobile_router.router_supplement_file_3
	 * @param routerSupplementFile3  the value for skf.skf2100_m_mobile_router.router_supplement_file_3
	 * @mbg.generated
	 */
	public void setRouterSupplementFile3(byte[] routerSupplementFile3) {
		this.routerSupplementFile3 = routerSupplementFile3;
	}
}