package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf2100TMobileRouterLedger extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.mobile_router_kanri_id
	 * @mbg.generated
	 */
	private Long mobileRouterKanriId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.mobile_router_no
	 * @mbg.generated
	 */
	private Long mobileRouterNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.original_company_cd
	 * @mbg.generated
	 */
	private String originalCompanyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.pay_company_cd
	 * @mbg.generated
	 */
	private String payCompanyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.hannyu_tel
	 * @mbg.generated
	 */
	private String hannyuTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.hannyu_mailaddress
	 * @mbg.generated
	 */
	private String hannyuMailaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.hannyu_appl_day
	 * @mbg.generated
	 */
	private String hannyuApplDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.use_start_hope_day
	 * @mbg.generated
	 */
	private String useStartHopeDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.shipping_date
	 * @mbg.generated
	 */
	private String shippingDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.received_date
	 * @mbg.generated
	 */
	private String receivedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.hanshutu_appl_day
	 * @mbg.generated
	 */
	private String hanshutuApplDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.use_stop_day
	 * @mbg.generated
	 */
	private String useStopDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.hansyutu_tel
	 * @mbg.generated
	 */
	private String hansyutuTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.return_day
	 * @mbg.generated
	 */
	private String returnDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2100_t_mobile_router_ledger.biko
	 * @mbg.generated
	 */
	private String biko;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2100_t_mobile_router_ledger
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.mobile_router_kanri_id
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.mobile_router_kanri_id
	 * @mbg.generated
	 */
	public Long getMobileRouterKanriId() {
		return mobileRouterKanriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.mobile_router_kanri_id
	 * @param mobileRouterKanriId  the value for skf.skf2100_t_mobile_router_ledger.mobile_router_kanri_id
	 * @mbg.generated
	 */
	public void setMobileRouterKanriId(Long mobileRouterKanriId) {
		this.mobileRouterKanriId = mobileRouterKanriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.mobile_router_no
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.mobile_router_no
	 * @mbg.generated
	 */
	public Long getMobileRouterNo() {
		return mobileRouterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.mobile_router_no
	 * @param mobileRouterNo  the value for skf.skf2100_t_mobile_router_ledger.mobile_router_no
	 * @mbg.generated
	 */
	public void setMobileRouterNo(Long mobileRouterNo) {
		this.mobileRouterNo = mobileRouterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.shain_no
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.shain_no
	 * @param shainNo  the value for skf.skf2100_t_mobile_router_ledger.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.original_company_cd
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.original_company_cd
	 * @mbg.generated
	 */
	public String getOriginalCompanyCd() {
		return originalCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.original_company_cd
	 * @param originalCompanyCd  the value for skf.skf2100_t_mobile_router_ledger.original_company_cd
	 * @mbg.generated
	 */
	public void setOriginalCompanyCd(String originalCompanyCd) {
		this.originalCompanyCd = originalCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.pay_company_cd
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.pay_company_cd
	 * @mbg.generated
	 */
	public String getPayCompanyCd() {
		return payCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.pay_company_cd
	 * @param payCompanyCd  the value for skf.skf2100_t_mobile_router_ledger.pay_company_cd
	 * @mbg.generated
	 */
	public void setPayCompanyCd(String payCompanyCd) {
		this.payCompanyCd = payCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.hannyu_tel
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.hannyu_tel
	 * @mbg.generated
	 */
	public String getHannyuTel() {
		return hannyuTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.hannyu_tel
	 * @param hannyuTel  the value for skf.skf2100_t_mobile_router_ledger.hannyu_tel
	 * @mbg.generated
	 */
	public void setHannyuTel(String hannyuTel) {
		this.hannyuTel = hannyuTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.hannyu_mailaddress
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.hannyu_mailaddress
	 * @mbg.generated
	 */
	public String getHannyuMailaddress() {
		return hannyuMailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.hannyu_mailaddress
	 * @param hannyuMailaddress  the value for skf.skf2100_t_mobile_router_ledger.hannyu_mailaddress
	 * @mbg.generated
	 */
	public void setHannyuMailaddress(String hannyuMailaddress) {
		this.hannyuMailaddress = hannyuMailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.hannyu_appl_day
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.hannyu_appl_day
	 * @mbg.generated
	 */
	public String getHannyuApplDay() {
		return hannyuApplDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.hannyu_appl_day
	 * @param hannyuApplDay  the value for skf.skf2100_t_mobile_router_ledger.hannyu_appl_day
	 * @mbg.generated
	 */
	public void setHannyuApplDay(String hannyuApplDay) {
		this.hannyuApplDay = hannyuApplDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.use_start_hope_day
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.use_start_hope_day
	 * @mbg.generated
	 */
	public String getUseStartHopeDay() {
		return useStartHopeDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.use_start_hope_day
	 * @param useStartHopeDay  the value for skf.skf2100_t_mobile_router_ledger.use_start_hope_day
	 * @mbg.generated
	 */
	public void setUseStartHopeDay(String useStartHopeDay) {
		this.useStartHopeDay = useStartHopeDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.shipping_date
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.shipping_date
	 * @mbg.generated
	 */
	public String getShippingDate() {
		return shippingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.shipping_date
	 * @param shippingDate  the value for skf.skf2100_t_mobile_router_ledger.shipping_date
	 * @mbg.generated
	 */
	public void setShippingDate(String shippingDate) {
		this.shippingDate = shippingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.received_date
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.received_date
	 * @mbg.generated
	 */
	public String getReceivedDate() {
		return receivedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.received_date
	 * @param receivedDate  the value for skf.skf2100_t_mobile_router_ledger.received_date
	 * @mbg.generated
	 */
	public void setReceivedDate(String receivedDate) {
		this.receivedDate = receivedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.hanshutu_appl_day
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.hanshutu_appl_day
	 * @mbg.generated
	 */
	public String getHanshutuApplDay() {
		return hanshutuApplDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.hanshutu_appl_day
	 * @param hanshutuApplDay  the value for skf.skf2100_t_mobile_router_ledger.hanshutu_appl_day
	 * @mbg.generated
	 */
	public void setHanshutuApplDay(String hanshutuApplDay) {
		this.hanshutuApplDay = hanshutuApplDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.use_stop_day
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.use_stop_day
	 * @mbg.generated
	 */
	public String getUseStopDay() {
		return useStopDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.use_stop_day
	 * @param useStopDay  the value for skf.skf2100_t_mobile_router_ledger.use_stop_day
	 * @mbg.generated
	 */
	public void setUseStopDay(String useStopDay) {
		this.useStopDay = useStopDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.hansyutu_tel
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.hansyutu_tel
	 * @mbg.generated
	 */
	public String getHansyutuTel() {
		return hansyutuTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.hansyutu_tel
	 * @param hansyutuTel  the value for skf.skf2100_t_mobile_router_ledger.hansyutu_tel
	 * @mbg.generated
	 */
	public void setHansyutuTel(String hansyutuTel) {
		this.hansyutuTel = hansyutuTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.return_day
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.return_day
	 * @mbg.generated
	 */
	public String getReturnDay() {
		return returnDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.return_day
	 * @param returnDay  the value for skf.skf2100_t_mobile_router_ledger.return_day
	 * @mbg.generated
	 */
	public void setReturnDay(String returnDay) {
		this.returnDay = returnDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2100_t_mobile_router_ledger.biko
	 * @return  the value of skf.skf2100_t_mobile_router_ledger.biko
	 * @mbg.generated
	 */
	public String getBiko() {
		return biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2100_t_mobile_router_ledger.biko
	 * @param biko  the value for skf.skf2100_t_mobile_router_ledger.biko
	 * @mbg.generated
	 */
	public void setBiko(String biko) {
		this.biko = biko;
	}
}