package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import java.util.Date;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf2010TApplHistoryKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.company_cd
	 * @mbg.generated
	 */
	private String companyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.appl_date
	 * @mbg.generated
	 */
	private Date applDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.appl_no
	 * @mbg.generated
	 */
	private String applNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.appl_id
	 * @mbg.generated
	 */
	private String applId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2010_t_appl_history
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.company_cd
	 * @return  the value of skf.skf2010_t_appl_history.company_cd
	 * @mbg.generated
	 */
	public String getCompanyCd() {
		return companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.company_cd
	 * @param companyCd  the value for skf.skf2010_t_appl_history.company_cd
	 * @mbg.generated
	 */
	public void setCompanyCd(String companyCd) {
		this.companyCd = companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.shain_no
	 * @return  the value of skf.skf2010_t_appl_history.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.shain_no
	 * @param shainNo  the value for skf.skf2010_t_appl_history.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.appl_date
	 * @return  the value of skf.skf2010_t_appl_history.appl_date
	 * @mbg.generated
	 */
	public Date getApplDate() {
		return applDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.appl_date
	 * @param applDate  the value for skf.skf2010_t_appl_history.appl_date
	 * @mbg.generated
	 */
	public void setApplDate(Date applDate) {
		this.applDate = applDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.appl_no
	 * @return  the value of skf.skf2010_t_appl_history.appl_no
	 * @mbg.generated
	 */
	public String getApplNo() {
		return applNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.appl_no
	 * @param applNo  the value for skf.skf2010_t_appl_history.appl_no
	 * @mbg.generated
	 */
	public void setApplNo(String applNo) {
		this.applNo = applNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.appl_id
	 * @return  the value of skf.skf2010_t_appl_history.appl_id
	 * @mbg.generated
	 */
	public String getApplId() {
		return applId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.appl_id
	 * @param applId  the value for skf.skf2010_t_appl_history.appl_id
	 * @mbg.generated
	 */
	public void setApplId(String applId) {
		this.applId = applId;
	}
}