package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf2060TKariageBukkenFileKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_bukken_file.company_cd
	 * @mbg.generated
	 */
	private String companyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_bukken_file.candidate_no
	 * @mbg.generated
	 */
	private Long candidateNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2060_t_kariage_bukken_file.attached_name
	 * @mbg.generated
	 */
	private String attachedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_bukken_file.company_cd
	 * @return  the value of skf.skf2060_t_kariage_bukken_file.company_cd
	 * @mbg.generated
	 */
	public String getCompanyCd() {
		return companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_bukken_file.company_cd
	 * @param companyCd  the value for skf.skf2060_t_kariage_bukken_file.company_cd
	 * @mbg.generated
	 */
	public void setCompanyCd(String companyCd) {
		this.companyCd = companyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_bukken_file.candidate_no
	 * @return  the value of skf.skf2060_t_kariage_bukken_file.candidate_no
	 * @mbg.generated
	 */
	public Long getCandidateNo() {
		return candidateNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_bukken_file.candidate_no
	 * @param candidateNo  the value for skf.skf2060_t_kariage_bukken_file.candidate_no
	 * @mbg.generated
	 */
	public void setCandidateNo(Long candidateNo) {
		this.candidateNo = candidateNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2060_t_kariage_bukken_file.attached_name
	 * @return  the value of skf.skf2060_t_kariage_bukken_file.attached_name
	 * @mbg.generated
	 */
	public String getAttachedName() {
		return attachedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2060_t_kariage_bukken_file.attached_name
	 * @param attachedName  the value for skf.skf2060_t_kariage_bukken_file.attached_name
	 * @mbg.generated
	 */
	public void setAttachedName(String attachedName) {
		this.attachedName = attachedName;
	}
}