package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import java.util.Date;

public class Skf2010TApplHistory extends Skf2010TApplHistoryKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.appl_status
	 * @mbg.generated
	 */
	private String applStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.appl_tac_flg
	 * @mbg.generated
	 */
	private String applTacFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.agre_date
	 * @mbg.generated
	 */
	private Date agreDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.agre_name1
	 * @mbg.generated
	 */
	private String agreName1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.agre_name2
	 * @mbg.generated
	 */
	private String agreName2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.agre_name3
	 * @mbg.generated
	 */
	private String agreName3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.agre_name4
	 * @mbg.generated
	 */
	private String agreName4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.agre_name5
	 * @mbg.generated
	 */
	private String agreName5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_history.combo_flg
	 * @mbg.generated
	 */
	private String comboFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2010_t_appl_history
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.appl_status
	 * @return  the value of skf.skf2010_t_appl_history.appl_status
	 * @mbg.generated
	 */
	public String getApplStatus() {
		return applStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.appl_status
	 * @param applStatus  the value for skf.skf2010_t_appl_history.appl_status
	 * @mbg.generated
	 */
	public void setApplStatus(String applStatus) {
		this.applStatus = applStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.appl_tac_flg
	 * @return  the value of skf.skf2010_t_appl_history.appl_tac_flg
	 * @mbg.generated
	 */
	public String getApplTacFlg() {
		return applTacFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.appl_tac_flg
	 * @param applTacFlg  the value for skf.skf2010_t_appl_history.appl_tac_flg
	 * @mbg.generated
	 */
	public void setApplTacFlg(String applTacFlg) {
		this.applTacFlg = applTacFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.agre_date
	 * @return  the value of skf.skf2010_t_appl_history.agre_date
	 * @mbg.generated
	 */
	public Date getAgreDate() {
		return agreDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.agre_date
	 * @param agreDate  the value for skf.skf2010_t_appl_history.agre_date
	 * @mbg.generated
	 */
	public void setAgreDate(Date agreDate) {
		this.agreDate = agreDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.agre_name1
	 * @return  the value of skf.skf2010_t_appl_history.agre_name1
	 * @mbg.generated
	 */
	public String getAgreName1() {
		return agreName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.agre_name1
	 * @param agreName1  the value for skf.skf2010_t_appl_history.agre_name1
	 * @mbg.generated
	 */
	public void setAgreName1(String agreName1) {
		this.agreName1 = agreName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.agre_name2
	 * @return  the value of skf.skf2010_t_appl_history.agre_name2
	 * @mbg.generated
	 */
	public String getAgreName2() {
		return agreName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.agre_name2
	 * @param agreName2  the value for skf.skf2010_t_appl_history.agre_name2
	 * @mbg.generated
	 */
	public void setAgreName2(String agreName2) {
		this.agreName2 = agreName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.agre_name3
	 * @return  the value of skf.skf2010_t_appl_history.agre_name3
	 * @mbg.generated
	 */
	public String getAgreName3() {
		return agreName3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.agre_name3
	 * @param agreName3  the value for skf.skf2010_t_appl_history.agre_name3
	 * @mbg.generated
	 */
	public void setAgreName3(String agreName3) {
		this.agreName3 = agreName3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.agre_name4
	 * @return  the value of skf.skf2010_t_appl_history.agre_name4
	 * @mbg.generated
	 */
	public String getAgreName4() {
		return agreName4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.agre_name4
	 * @param agreName4  the value for skf.skf2010_t_appl_history.agre_name4
	 * @mbg.generated
	 */
	public void setAgreName4(String agreName4) {
		this.agreName4 = agreName4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.agre_name5
	 * @return  the value of skf.skf2010_t_appl_history.agre_name5
	 * @mbg.generated
	 */
	public String getAgreName5() {
		return agreName5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.agre_name5
	 * @param agreName5  the value for skf.skf2010_t_appl_history.agre_name5
	 * @mbg.generated
	 */
	public void setAgreName5(String agreName5) {
		this.agreName5 = agreName5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_history.combo_flg
	 * @return  the value of skf.skf2010_t_appl_history.combo_flg
	 * @mbg.generated
	 */
	public String getComboFlg() {
		return comboFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_history.combo_flg
	 * @param comboFlg  the value for skf.skf2010_t_appl_history.combo_flg
	 * @mbg.generated
	 */
	public void setComboFlg(String comboFlg) {
		this.comboFlg = comboFlg;
	}
}