package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2010MWorkflow extends Skf2010MWorkflowKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_m_workflow.wf_name
	 * @mbg.generated
	 */
	private String wfName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2010_m_workflow
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_m_workflow.wf_name
	 * @return  the value of skf.skf2010_m_workflow.wf_name
	 * @mbg.generated
	 */
	public String getWfName() {
		return wfName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_m_workflow.wf_name
	 * @param wfName  the value for skf.skf2010_m_workflow.wf_name
	 * @mbg.generated
	 */
	public void setWfName(String wfName) {
		this.wfName = wfName;
	}
}