package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf2010TApplComment extends Skf2010TApplCommentKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_comment.comment_name
	 * @mbg.generated
	 */
	private String commentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf2010_t_appl_comment.comment_note
	 * @mbg.generated
	 */
	private String commentNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf2010_t_appl_comment
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_comment.comment_name
	 * @return  the value of skf.skf2010_t_appl_comment.comment_name
	 * @mbg.generated
	 */
	public String getCommentName() {
		return commentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_comment.comment_name
	 * @param commentName  the value for skf.skf2010_t_appl_comment.comment_name
	 * @mbg.generated
	 */
	public void setCommentName(String commentName) {
		this.commentName = commentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf2010_t_appl_comment.comment_note
	 * @return  the value of skf.skf2010_t_appl_comment.comment_note
	 * @mbg.generated
	 */
	public String getCommentNote() {
		return commentNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf2010_t_appl_comment.comment_note
	 * @param commentNote  the value for skf.skf2010_t_appl_comment.comment_note
	 * @mbg.generated
	 */
	public void setCommentNote(String commentNote) {
		this.commentNote = commentNote;
	}
}