package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3022MAgingResidualRateKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3022_m_aging_residual_rate.aging_minimum
	 * @mbg.generated
	 */
	private Short agingMinimum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3022_m_aging_residual_rate.structure_kbn
	 * @mbg.generated
	 */
	private String structureKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3022_m_aging_residual_rate
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3022_m_aging_residual_rate.aging_minimum
	 * @return  the value of skf.skf3022_m_aging_residual_rate.aging_minimum
	 * @mbg.generated
	 */
	public Short getAgingMinimum() {
		return agingMinimum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3022_m_aging_residual_rate.aging_minimum
	 * @param agingMinimum  the value for skf.skf3022_m_aging_residual_rate.aging_minimum
	 * @mbg.generated
	 */
	public void setAgingMinimum(Short agingMinimum) {
		this.agingMinimum = agingMinimum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3022_m_aging_residual_rate.structure_kbn
	 * @return  the value of skf.skf3022_m_aging_residual_rate.structure_kbn
	 * @mbg.generated
	 */
	public String getStructureKbn() {
		return structureKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3022_m_aging_residual_rate.structure_kbn
	 * @param structureKbn  the value for skf.skf3022_m_aging_residual_rate.structure_kbn
	 * @mbg.generated
	 */
	public void setStructureKbn(String structureKbn) {
		this.structureKbn = structureKbn;
	}
}