package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3010MShatakuParkingContract extends Skf3010MShatakuParkingContractKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.owner_no
	 * @mbg.generated
	 */
	private Long ownerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.asset_register_no
	 * @mbg.generated
	 */
	private String assetRegisterNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.contract_start_date
	 * @mbg.generated
	 */
	private String contractStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.contract_end_date
	 * @mbg.generated
	 */
	private String contractEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.land_rent
	 * @mbg.generated
	 */
	private Integer landRent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.biko
	 * @mbg.generated
	 */
	private String biko;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.parking_contract_type
	 * @mbg.generated
	 */
	private String parkingContractType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.parking_address_kbn
	 * @mbg.generated
	 */
	private String parkingAddressKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.parking_name
	 * @mbg.generated
	 */
	private String parkingName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.parking_zip_cd
	 * @mbg.generated
	 */
	private String parkingZipCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_parking_contract.parking_address
	 * @mbg.generated
	 */
	private String parkingAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3010_m_shataku_parking_contract
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.owner_no
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.owner_no
	 * @mbg.generated
	 */
	public Long getOwnerNo() {
		return ownerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.owner_no
	 * @param ownerNo  the value for skf.skf3010_m_shataku_parking_contract.owner_no
	 * @mbg.generated
	 */
	public void setOwnerNo(Long ownerNo) {
		this.ownerNo = ownerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.asset_register_no
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.asset_register_no
	 * @mbg.generated
	 */
	public String getAssetRegisterNo() {
		return assetRegisterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.asset_register_no
	 * @param assetRegisterNo  the value for skf.skf3010_m_shataku_parking_contract.asset_register_no
	 * @mbg.generated
	 */
	public void setAssetRegisterNo(String assetRegisterNo) {
		this.assetRegisterNo = assetRegisterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.contract_start_date
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.contract_start_date
	 * @mbg.generated
	 */
	public String getContractStartDate() {
		return contractStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.contract_start_date
	 * @param contractStartDate  the value for skf.skf3010_m_shataku_parking_contract.contract_start_date
	 * @mbg.generated
	 */
	public void setContractStartDate(String contractStartDate) {
		this.contractStartDate = contractStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.contract_end_date
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.contract_end_date
	 * @mbg.generated
	 */
	public String getContractEndDate() {
		return contractEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.contract_end_date
	 * @param contractEndDate  the value for skf.skf3010_m_shataku_parking_contract.contract_end_date
	 * @mbg.generated
	 */
	public void setContractEndDate(String contractEndDate) {
		this.contractEndDate = contractEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.land_rent
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.land_rent
	 * @mbg.generated
	 */
	public Integer getLandRent() {
		return landRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.land_rent
	 * @param landRent  the value for skf.skf3010_m_shataku_parking_contract.land_rent
	 * @mbg.generated
	 */
	public void setLandRent(Integer landRent) {
		this.landRent = landRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.biko
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.biko
	 * @mbg.generated
	 */
	public String getBiko() {
		return biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.biko
	 * @param biko  the value for skf.skf3010_m_shataku_parking_contract.biko
	 * @mbg.generated
	 */
	public void setBiko(String biko) {
		this.biko = biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.parking_contract_type
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.parking_contract_type
	 * @mbg.generated
	 */
	public String getParkingContractType() {
		return parkingContractType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.parking_contract_type
	 * @param parkingContractType  the value for skf.skf3010_m_shataku_parking_contract.parking_contract_type
	 * @mbg.generated
	 */
	public void setParkingContractType(String parkingContractType) {
		this.parkingContractType = parkingContractType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.parking_address_kbn
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.parking_address_kbn
	 * @mbg.generated
	 */
	public String getParkingAddressKbn() {
		return parkingAddressKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.parking_address_kbn
	 * @param parkingAddressKbn  the value for skf.skf3010_m_shataku_parking_contract.parking_address_kbn
	 * @mbg.generated
	 */
	public void setParkingAddressKbn(String parkingAddressKbn) {
		this.parkingAddressKbn = parkingAddressKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.parking_name
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.parking_name
	 * @mbg.generated
	 */
	public String getParkingName() {
		return parkingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.parking_name
	 * @param parkingName  the value for skf.skf3010_m_shataku_parking_contract.parking_name
	 * @mbg.generated
	 */
	public void setParkingName(String parkingName) {
		this.parkingName = parkingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.parking_zip_cd
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.parking_zip_cd
	 * @mbg.generated
	 */
	public String getParkingZipCd() {
		return parkingZipCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.parking_zip_cd
	 * @param parkingZipCd  the value for skf.skf3010_m_shataku_parking_contract.parking_zip_cd
	 * @mbg.generated
	 */
	public void setParkingZipCd(String parkingZipCd) {
		this.parkingZipCd = parkingZipCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_parking_contract.parking_address
	 * @return  the value of skf.skf3010_m_shataku_parking_contract.parking_address
	 * @mbg.generated
	 */
	public String getParkingAddress() {
		return parkingAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_parking_contract.parking_address
	 * @param parkingAddress  the value for skf.skf3010_m_shataku_parking_contract.parking_address
	 * @mbg.generated
	 */
	public void setParkingAddress(String parkingAddress) {
		this.parkingAddress = parkingAddress;
	}
}