package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3022TShatakuYoyakuDataKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3022_t_shataku_yoyaku_data.shataku_yoyaku_id
	 * @mbg.generated
	 */
	private Long shatakuYoyakuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3022_t_shataku_yoyaku_data.year_month
	 * @mbg.generated
	 */
	private String yearMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3022_t_shataku_yoyaku_data
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3022_t_shataku_yoyaku_data.shataku_yoyaku_id
	 * @return  the value of skf.skf3022_t_shataku_yoyaku_data.shataku_yoyaku_id
	 * @mbg.generated
	 */
	public Long getShatakuYoyakuId() {
		return shatakuYoyakuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3022_t_shataku_yoyaku_data.shataku_yoyaku_id
	 * @param shatakuYoyakuId  the value for skf.skf3022_t_shataku_yoyaku_data.shataku_yoyaku_id
	 * @mbg.generated
	 */
	public void setShatakuYoyakuId(Long shatakuYoyakuId) {
		this.shatakuYoyakuId = shatakuYoyakuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3022_t_shataku_yoyaku_data.year_month
	 * @return  the value of skf.skf3022_t_shataku_yoyaku_data.year_month
	 * @mbg.generated
	 */
	public String getYearMonth() {
		return yearMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3022_t_shataku_yoyaku_data.year_month
	 * @param yearMonth  the value for skf.skf3022_t_shataku_yoyaku_data.year_month
	 * @mbg.generated
	 */
	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}
}