package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3060TAgeKasanSendmail extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3060_t_age_kasan_sendmail.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3060_t_age_kasan_sendmail.send_mail_date1
	 * @mbg.generated
	 */
	private String sendMailDate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3060_t_age_kasan_sendmail.send_mail_date2
	 * @mbg.generated
	 */
	private String sendMailDate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3060_t_age_kasan_sendmail
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3060_t_age_kasan_sendmail.shain_no
	 * @return  the value of skf.skf3060_t_age_kasan_sendmail.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3060_t_age_kasan_sendmail.shain_no
	 * @param shainNo  the value for skf.skf3060_t_age_kasan_sendmail.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3060_t_age_kasan_sendmail.send_mail_date1
	 * @return  the value of skf.skf3060_t_age_kasan_sendmail.send_mail_date1
	 * @mbg.generated
	 */
	public String getSendMailDate1() {
		return sendMailDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3060_t_age_kasan_sendmail.send_mail_date1
	 * @param sendMailDate1  the value for skf.skf3060_t_age_kasan_sendmail.send_mail_date1
	 * @mbg.generated
	 */
	public void setSendMailDate1(String sendMailDate1) {
		this.sendMailDate1 = sendMailDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3060_t_age_kasan_sendmail.send_mail_date2
	 * @return  the value of skf.skf3060_t_age_kasan_sendmail.send_mail_date2
	 * @mbg.generated
	 */
	public String getSendMailDate2() {
		return sendMailDate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3060_t_age_kasan_sendmail.send_mail_date2
	 * @param sendMailDate2  the value for skf.skf3060_t_age_kasan_sendmail.send_mail_date2
	 * @mbg.generated
	 */
	public void setSendMailDate2(String sendMailDate2) {
		this.sendMailDate2 = sendMailDate2;
	}
}