package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3050MGeneralEquipmentItemKey extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skf.skf3050_m_general_equipment_item.general_equipment_cd
     *
     * @mbg.generated
     */
    private String generalEquipmentCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skf.skf3050_m_general_equipment_item.start_year_month
     *
     * @mbg.generated
     */
    private String startYearMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skf.skf3050_m_general_equipment_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skf.skf3050_m_general_equipment_item.general_equipment_cd
     *
     * @return the value of skf.skf3050_m_general_equipment_item.general_equipment_cd
     *
     * @mbg.generated
     */
    public String getGeneralEquipmentCd() {
        return generalEquipmentCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skf.skf3050_m_general_equipment_item.general_equipment_cd
     *
     * @param generalEquipmentCd the value for skf.skf3050_m_general_equipment_item.general_equipment_cd
     *
     * @mbg.generated
     */
    public void setGeneralEquipmentCd(String generalEquipmentCd) {
        this.generalEquipmentCd = generalEquipmentCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skf.skf3050_m_general_equipment_item.start_year_month
     *
     * @return the value of skf.skf3050_m_general_equipment_item.start_year_month
     *
     * @mbg.generated
     */
    public String getStartYearMonth() {
        return startYearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skf.skf3050_m_general_equipment_item.start_year_month
     *
     * @param startYearMonth the value for skf.skf3050_m_general_equipment_item.start_year_month
     *
     * @mbg.generated
     */
    public void setStartYearMonth(String startYearMonth) {
        this.startYearMonth = startYearMonth;
    }
}