package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3030TShatakuMutualRireki extends Skf3030TShatakuMutualRirekiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual_rireki.assign_company_cd
	 * @mbg.generated
	 */
	private String assignCompanyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual_rireki.assign_agency_name
	 * @mbg.generated
	 */
	private String assignAgencyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual_rireki.assign_affiliation1
	 * @mbg.generated
	 */
	private String assignAffiliation1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual_rireki.assign_affiliation2
	 * @mbg.generated
	 */
	private String assignAffiliation2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual_rireki.assign_cd
	 * @mbg.generated
	 */
	private String assignCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3030_t_shataku_mutual_rireki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_company_cd
	 * @return  the value of skf.skf3030_t_shataku_mutual_rireki.assign_company_cd
	 * @mbg.generated
	 */
	public String getAssignCompanyCd() {
		return assignCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_company_cd
	 * @param assignCompanyCd  the value for skf.skf3030_t_shataku_mutual_rireki.assign_company_cd
	 * @mbg.generated
	 */
	public void setAssignCompanyCd(String assignCompanyCd) {
		this.assignCompanyCd = assignCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_agency_name
	 * @return  the value of skf.skf3030_t_shataku_mutual_rireki.assign_agency_name
	 * @mbg.generated
	 */
	public String getAssignAgencyName() {
		return assignAgencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_agency_name
	 * @param assignAgencyName  the value for skf.skf3030_t_shataku_mutual_rireki.assign_agency_name
	 * @mbg.generated
	 */
	public void setAssignAgencyName(String assignAgencyName) {
		this.assignAgencyName = assignAgencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_affiliation1
	 * @return  the value of skf.skf3030_t_shataku_mutual_rireki.assign_affiliation1
	 * @mbg.generated
	 */
	public String getAssignAffiliation1() {
		return assignAffiliation1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_affiliation1
	 * @param assignAffiliation1  the value for skf.skf3030_t_shataku_mutual_rireki.assign_affiliation1
	 * @mbg.generated
	 */
	public void setAssignAffiliation1(String assignAffiliation1) {
		this.assignAffiliation1 = assignAffiliation1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_affiliation2
	 * @return  the value of skf.skf3030_t_shataku_mutual_rireki.assign_affiliation2
	 * @mbg.generated
	 */
	public String getAssignAffiliation2() {
		return assignAffiliation2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_affiliation2
	 * @param assignAffiliation2  the value for skf.skf3030_t_shataku_mutual_rireki.assign_affiliation2
	 * @mbg.generated
	 */
	public void setAssignAffiliation2(String assignAffiliation2) {
		this.assignAffiliation2 = assignAffiliation2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_cd
	 * @return  the value of skf.skf3030_t_shataku_mutual_rireki.assign_cd
	 * @mbg.generated
	 */
	public String getAssignCd() {
		return assignCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual_rireki.assign_cd
	 * @param assignCd  the value for skf.skf3030_t_shataku_mutual_rireki.assign_cd
	 * @mbg.generated
	 */
	public void setAssignCd(String assignCd) {
		this.assignCd = assignCd;
	}
}