package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3050MAccount extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_account.account_id
	 * @mbg.generated
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_account.account_code
	 * @mbg.generated
	 */
	private String accountCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_account.account_name
	 * @mbg.generated
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3050_m_account
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_account.account_id
	 * @return  the value of skf.skf3050_m_account.account_id
	 * @mbg.generated
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_account.account_id
	 * @param accountId  the value for skf.skf3050_m_account.account_id
	 * @mbg.generated
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_account.account_code
	 * @return  the value of skf.skf3050_m_account.account_code
	 * @mbg.generated
	 */
	public String getAccountCode() {
		return accountCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_account.account_code
	 * @param accountCode  the value for skf.skf3050_m_account.account_code
	 * @mbg.generated
	 */
	public void setAccountCode(String accountCode) {
		this.accountCode = accountCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_account.account_name
	 * @return  the value of skf.skf3050_m_account.account_name
	 * @mbg.generated
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_account.account_name
	 * @param accountName  the value for skf.skf3050_m_account.account_name
	 * @mbg.generated
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}
}