package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3020TTenninshaChoshoData extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.tokyu
	 * @mbg.generated
	 */
	private String tokyu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.age
	 * @mbg.generated
	 */
	private String age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.now_affiliation
	 * @mbg.generated
	 */
	private String nowAffiliation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.new_affiliation
	 * @mbg.generated
	 */
	private String newAffiliation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.biko
	 * @mbg.generated
	 */
	private String biko;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.shain_no_henko_kbn
	 * @mbg.generated
	 */
	private String shainNoHenkoKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.nyukyo_flg
	 * @mbg.generated
	 */
	private String nyukyoFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.taikyo_flg
	 * @mbg.generated
	 */
	private String taikyoFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.henkou_flg
	 * @mbg.generated
	 */
	private String henkouFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.now_shataku_kbn
	 * @mbg.generated
	 */
	private String nowShatakuKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.nyutaikyo_yotei_kbn
	 * @mbg.generated
	 */
	private String nyutaikyoYoteiKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3020_t_tenninsha_chosho_data.data_takingin_date
	 * @mbg.generated
	 */
	private String dataTakinginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3020_t_tenninsha_chosho_data
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.shain_no
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.shain_no
	 * @param shainNo  the value for skf.skf3020_t_tenninsha_chosho_data.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.name
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.name
	 * @param name  the value for skf.skf3020_t_tenninsha_chosho_data.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.tokyu
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.tokyu
	 * @mbg.generated
	 */
	public String getTokyu() {
		return tokyu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.tokyu
	 * @param tokyu  the value for skf.skf3020_t_tenninsha_chosho_data.tokyu
	 * @mbg.generated
	 */
	public void setTokyu(String tokyu) {
		this.tokyu = tokyu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.age
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.age
	 * @mbg.generated
	 */
	public String getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.age
	 * @param age  the value for skf.skf3020_t_tenninsha_chosho_data.age
	 * @mbg.generated
	 */
	public void setAge(String age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.now_affiliation
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.now_affiliation
	 * @mbg.generated
	 */
	public String getNowAffiliation() {
		return nowAffiliation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.now_affiliation
	 * @param nowAffiliation  the value for skf.skf3020_t_tenninsha_chosho_data.now_affiliation
	 * @mbg.generated
	 */
	public void setNowAffiliation(String nowAffiliation) {
		this.nowAffiliation = nowAffiliation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.new_affiliation
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.new_affiliation
	 * @mbg.generated
	 */
	public String getNewAffiliation() {
		return newAffiliation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.new_affiliation
	 * @param newAffiliation  the value for skf.skf3020_t_tenninsha_chosho_data.new_affiliation
	 * @mbg.generated
	 */
	public void setNewAffiliation(String newAffiliation) {
		this.newAffiliation = newAffiliation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.biko
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.biko
	 * @mbg.generated
	 */
	public String getBiko() {
		return biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.biko
	 * @param biko  the value for skf.skf3020_t_tenninsha_chosho_data.biko
	 * @mbg.generated
	 */
	public void setBiko(String biko) {
		this.biko = biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.shain_no_henko_kbn
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.shain_no_henko_kbn
	 * @mbg.generated
	 */
	public String getShainNoHenkoKbn() {
		return shainNoHenkoKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.shain_no_henko_kbn
	 * @param shainNoHenkoKbn  the value for skf.skf3020_t_tenninsha_chosho_data.shain_no_henko_kbn
	 * @mbg.generated
	 */
	public void setShainNoHenkoKbn(String shainNoHenkoKbn) {
		this.shainNoHenkoKbn = shainNoHenkoKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.nyukyo_flg
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.nyukyo_flg
	 * @mbg.generated
	 */
	public String getNyukyoFlg() {
		return nyukyoFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.nyukyo_flg
	 * @param nyukyoFlg  the value for skf.skf3020_t_tenninsha_chosho_data.nyukyo_flg
	 * @mbg.generated
	 */
	public void setNyukyoFlg(String nyukyoFlg) {
		this.nyukyoFlg = nyukyoFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.taikyo_flg
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.taikyo_flg
	 * @mbg.generated
	 */
	public String getTaikyoFlg() {
		return taikyoFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.taikyo_flg
	 * @param taikyoFlg  the value for skf.skf3020_t_tenninsha_chosho_data.taikyo_flg
	 * @mbg.generated
	 */
	public void setTaikyoFlg(String taikyoFlg) {
		this.taikyoFlg = taikyoFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.henkou_flg
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.henkou_flg
	 * @mbg.generated
	 */
	public String getHenkouFlg() {
		return henkouFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.henkou_flg
	 * @param henkouFlg  the value for skf.skf3020_t_tenninsha_chosho_data.henkou_flg
	 * @mbg.generated
	 */
	public void setHenkouFlg(String henkouFlg) {
		this.henkouFlg = henkouFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.now_shataku_kbn
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.now_shataku_kbn
	 * @mbg.generated
	 */
	public String getNowShatakuKbn() {
		return nowShatakuKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.now_shataku_kbn
	 * @param nowShatakuKbn  the value for skf.skf3020_t_tenninsha_chosho_data.now_shataku_kbn
	 * @mbg.generated
	 */
	public void setNowShatakuKbn(String nowShatakuKbn) {
		this.nowShatakuKbn = nowShatakuKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.nyutaikyo_yotei_kbn
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.nyutaikyo_yotei_kbn
	 * @mbg.generated
	 */
	public String getNyutaikyoYoteiKbn() {
		return nyutaikyoYoteiKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.nyutaikyo_yotei_kbn
	 * @param nyutaikyoYoteiKbn  the value for skf.skf3020_t_tenninsha_chosho_data.nyutaikyo_yotei_kbn
	 * @mbg.generated
	 */
	public void setNyutaikyoYoteiKbn(String nyutaikyoYoteiKbn) {
		this.nyutaikyoYoteiKbn = nyutaikyoYoteiKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3020_t_tenninsha_chosho_data.data_takingin_date
	 * @return  the value of skf.skf3020_t_tenninsha_chosho_data.data_takingin_date
	 * @mbg.generated
	 */
	public String getDataTakinginDate() {
		return dataTakinginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3020_t_tenninsha_chosho_data.data_takingin_date
	 * @param dataTakinginDate  the value for skf.skf3020_t_tenninsha_chosho_data.data_takingin_date
	 * @mbg.generated
	 */
	public void setDataTakinginDate(String dataTakinginDate) {
		this.dataTakinginDate = dataTakinginDate;
	}
}