package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3010MShatakuRoomBihinKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_room_bihin.shataku_kanri_no
	 * @mbg.generated
	 */
	private Long shatakuKanriNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_room_bihin.shataku_room_kanri_no
	 * @mbg.generated
	 */
	private Long shatakuRoomKanriNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_room_bihin.bihin_cd
	 * @mbg.generated
	 */
	private String bihinCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3010_m_shataku_room_bihin
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_room_bihin.shataku_kanri_no
	 * @return  the value of skf.skf3010_m_shataku_room_bihin.shataku_kanri_no
	 * @mbg.generated
	 */
	public Long getShatakuKanriNo() {
		return shatakuKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_room_bihin.shataku_kanri_no
	 * @param shatakuKanriNo  the value for skf.skf3010_m_shataku_room_bihin.shataku_kanri_no
	 * @mbg.generated
	 */
	public void setShatakuKanriNo(Long shatakuKanriNo) {
		this.shatakuKanriNo = shatakuKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_room_bihin.shataku_room_kanri_no
	 * @return  the value of skf.skf3010_m_shataku_room_bihin.shataku_room_kanri_no
	 * @mbg.generated
	 */
	public Long getShatakuRoomKanriNo() {
		return shatakuRoomKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_room_bihin.shataku_room_kanri_no
	 * @param shatakuRoomKanriNo  the value for skf.skf3010_m_shataku_room_bihin.shataku_room_kanri_no
	 * @mbg.generated
	 */
	public void setShatakuRoomKanriNo(Long shatakuRoomKanriNo) {
		this.shatakuRoomKanriNo = shatakuRoomKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_room_bihin.bihin_cd
	 * @return  the value of skf.skf3010_m_shataku_room_bihin.bihin_cd
	 * @mbg.generated
	 */
	public String getBihinCd() {
		return bihinCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_room_bihin.bihin_cd
	 * @param bihinCd  the value for skf.skf3010_m_shataku_room_bihin.bihin_cd
	 * @mbg.generated
	 */
	public void setBihinCd(String bihinCd) {
		this.bihinCd = bihinCd;
	}
}