package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3050MRentalBase extends Skf3050MRentalBaseKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_rental_base.base_rental
	 * @mbg.generated
	 */
	private Integer baseRental;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3050_m_rental_base
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_rental_base.base_rental
	 * @return  the value of skf.skf3050_m_rental_base.base_rental
	 * @mbg.generated
	 */
	public Integer getBaseRental() {
		return baseRental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_rental_base.base_rental
	 * @param baseRental  the value for skf.skf3050_m_rental_base.base_rental
	 * @mbg.generated
	 */
	public void setBaseRental(Integer baseRental) {
		this.baseRental = baseRental;
	}
}