package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3030TParkingRirekiKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_parking_rireki.shataku_kanri_id
	 * @mbg.generated
	 */
	private Long shatakuKanriId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_parking_rireki.parking_lend_no
	 * @mbg.generated
	 */
	private Long parkingLendNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_parking_rireki.year_month
	 * @mbg.generated
	 */
	private String yearMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_parking_rireki.shataku_kanri_id
	 * @return  the value of skf.skf3030_t_parking_rireki.shataku_kanri_id
	 * @mbg.generated
	 */
	public Long getShatakuKanriId() {
		return shatakuKanriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_parking_rireki.shataku_kanri_id
	 * @param shatakuKanriId  the value for skf.skf3030_t_parking_rireki.shataku_kanri_id
	 * @mbg.generated
	 */
	public void setShatakuKanriId(Long shatakuKanriId) {
		this.shatakuKanriId = shatakuKanriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_parking_rireki.parking_lend_no
	 * @return  the value of skf.skf3030_t_parking_rireki.parking_lend_no
	 * @mbg.generated
	 */
	public Long getParkingLendNo() {
		return parkingLendNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_parking_rireki.parking_lend_no
	 * @param parkingLendNo  the value for skf.skf3030_t_parking_rireki.parking_lend_no
	 * @mbg.generated
	 */
	public void setParkingLendNo(Long parkingLendNo) {
		this.parkingLendNo = parkingLendNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_parking_rireki.year_month
	 * @return  the value of skf.skf3030_t_parking_rireki.year_month
	 * @mbg.generated
	 */
	public String getYearMonth() {
		return yearMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_parking_rireki.year_month
	 * @param yearMonth  the value for skf.skf3030_t_parking_rireki.year_month
	 * @mbg.generated
	 */
	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}
}