package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import java.math.BigDecimal;

public class Skf3030TRentalPattern extends Skf3030TRentalPatternKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.rental_pattern_name
	 * @mbg.generated
	 */
	private String rentalPatternName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.kikaku
	 * @mbg.generated
	 */
	private String kikaku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.kikaku_hosoku
	 * @mbg.generated
	 */
	private String kikakuHosoku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.base_calc_menseki
	 * @mbg.generated
	 */
	private BigDecimal baseCalcMenseki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.ause
	 * @mbg.generated
	 */
	private String ause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.kanreiti_flg
	 * @mbg.generated
	 */
	private String kanreitiFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.kyosyo_flg
	 * @mbg.generated
	 */
	private String kyosyoFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.aging
	 * @mbg.generated
	 */
	private Short aging;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.base_rental
	 * @mbg.generated
	 */
	private Integer baseRental;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.price
	 * @mbg.generated
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.rental
	 * @mbg.generated
	 */
	private Integer rental;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_name
	 * @mbg.generated
	 */
	private String shiryoHosokuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.biko
	 * @mbg.generated
	 */
	private String biko;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_size
	 * @mbg.generated
	 */
	private String shiryoHosokuSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.shataku_calc_menseki
	 * @mbg.generated
	 */
	private Short shatakuCalcMenseki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.aging_residual_rate
	 * @mbg.generated
	 */
	private BigDecimal agingResidualRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.menseki
	 * @mbg.generated
	 */
	private BigDecimal menseki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.sun_room_menseki
	 * @mbg.generated
	 */
	private BigDecimal sunRoomMenseki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.stairs_menseki
	 * @mbg.generated
	 */
	private BigDecimal stairsMenseki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.barn_menseki
	 * @mbg.generated
	 */
	private BigDecimal barnMenseki;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_file
	 * @mbg.generated
	 */
	private byte[] shiryoHosokuFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3030_t_rental_pattern
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.rental_pattern_name
	 * @return  the value of skf.skf3030_t_rental_pattern.rental_pattern_name
	 * @mbg.generated
	 */
	public String getRentalPatternName() {
		return rentalPatternName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.rental_pattern_name
	 * @param rentalPatternName  the value for skf.skf3030_t_rental_pattern.rental_pattern_name
	 * @mbg.generated
	 */
	public void setRentalPatternName(String rentalPatternName) {
		this.rentalPatternName = rentalPatternName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.kikaku
	 * @return  the value of skf.skf3030_t_rental_pattern.kikaku
	 * @mbg.generated
	 */
	public String getKikaku() {
		return kikaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.kikaku
	 * @param kikaku  the value for skf.skf3030_t_rental_pattern.kikaku
	 * @mbg.generated
	 */
	public void setKikaku(String kikaku) {
		this.kikaku = kikaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.kikaku_hosoku
	 * @return  the value of skf.skf3030_t_rental_pattern.kikaku_hosoku
	 * @mbg.generated
	 */
	public String getKikakuHosoku() {
		return kikakuHosoku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.kikaku_hosoku
	 * @param kikakuHosoku  the value for skf.skf3030_t_rental_pattern.kikaku_hosoku
	 * @mbg.generated
	 */
	public void setKikakuHosoku(String kikakuHosoku) {
		this.kikakuHosoku = kikakuHosoku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.base_calc_menseki
	 * @return  the value of skf.skf3030_t_rental_pattern.base_calc_menseki
	 * @mbg.generated
	 */
	public BigDecimal getBaseCalcMenseki() {
		return baseCalcMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.base_calc_menseki
	 * @param baseCalcMenseki  the value for skf.skf3030_t_rental_pattern.base_calc_menseki
	 * @mbg.generated
	 */
	public void setBaseCalcMenseki(BigDecimal baseCalcMenseki) {
		this.baseCalcMenseki = baseCalcMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.ause
	 * @return  the value of skf.skf3030_t_rental_pattern.ause
	 * @mbg.generated
	 */
	public String getAuse() {
		return ause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.ause
	 * @param ause  the value for skf.skf3030_t_rental_pattern.ause
	 * @mbg.generated
	 */
	public void setAuse(String ause) {
		this.ause = ause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.kanreiti_flg
	 * @return  the value of skf.skf3030_t_rental_pattern.kanreiti_flg
	 * @mbg.generated
	 */
	public String getKanreitiFlg() {
		return kanreitiFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.kanreiti_flg
	 * @param kanreitiFlg  the value for skf.skf3030_t_rental_pattern.kanreiti_flg
	 * @mbg.generated
	 */
	public void setKanreitiFlg(String kanreitiFlg) {
		this.kanreitiFlg = kanreitiFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.kyosyo_flg
	 * @return  the value of skf.skf3030_t_rental_pattern.kyosyo_flg
	 * @mbg.generated
	 */
	public String getKyosyoFlg() {
		return kyosyoFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.kyosyo_flg
	 * @param kyosyoFlg  the value for skf.skf3030_t_rental_pattern.kyosyo_flg
	 * @mbg.generated
	 */
	public void setKyosyoFlg(String kyosyoFlg) {
		this.kyosyoFlg = kyosyoFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.aging
	 * @return  the value of skf.skf3030_t_rental_pattern.aging
	 * @mbg.generated
	 */
	public Short getAging() {
		return aging;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.aging
	 * @param aging  the value for skf.skf3030_t_rental_pattern.aging
	 * @mbg.generated
	 */
	public void setAging(Short aging) {
		this.aging = aging;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.base_rental
	 * @return  the value of skf.skf3030_t_rental_pattern.base_rental
	 * @mbg.generated
	 */
	public Integer getBaseRental() {
		return baseRental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.base_rental
	 * @param baseRental  the value for skf.skf3030_t_rental_pattern.base_rental
	 * @mbg.generated
	 */
	public void setBaseRental(Integer baseRental) {
		this.baseRental = baseRental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.price
	 * @return  the value of skf.skf3030_t_rental_pattern.price
	 * @mbg.generated
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.price
	 * @param price  the value for skf.skf3030_t_rental_pattern.price
	 * @mbg.generated
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.rental
	 * @return  the value of skf.skf3030_t_rental_pattern.rental
	 * @mbg.generated
	 */
	public Integer getRental() {
		return rental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.rental
	 * @param rental  the value for skf.skf3030_t_rental_pattern.rental
	 * @mbg.generated
	 */
	public void setRental(Integer rental) {
		this.rental = rental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_name
	 * @return  the value of skf.skf3030_t_rental_pattern.shiryo_hosoku_name
	 * @mbg.generated
	 */
	public String getShiryoHosokuName() {
		return shiryoHosokuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_name
	 * @param shiryoHosokuName  the value for skf.skf3030_t_rental_pattern.shiryo_hosoku_name
	 * @mbg.generated
	 */
	public void setShiryoHosokuName(String shiryoHosokuName) {
		this.shiryoHosokuName = shiryoHosokuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.biko
	 * @return  the value of skf.skf3030_t_rental_pattern.biko
	 * @mbg.generated
	 */
	public String getBiko() {
		return biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.biko
	 * @param biko  the value for skf.skf3030_t_rental_pattern.biko
	 * @mbg.generated
	 */
	public void setBiko(String biko) {
		this.biko = biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_size
	 * @return  the value of skf.skf3030_t_rental_pattern.shiryo_hosoku_size
	 * @mbg.generated
	 */
	public String getShiryoHosokuSize() {
		return shiryoHosokuSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_size
	 * @param shiryoHosokuSize  the value for skf.skf3030_t_rental_pattern.shiryo_hosoku_size
	 * @mbg.generated
	 */
	public void setShiryoHosokuSize(String shiryoHosokuSize) {
		this.shiryoHosokuSize = shiryoHosokuSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.shataku_calc_menseki
	 * @return  the value of skf.skf3030_t_rental_pattern.shataku_calc_menseki
	 * @mbg.generated
	 */
	public Short getShatakuCalcMenseki() {
		return shatakuCalcMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.shataku_calc_menseki
	 * @param shatakuCalcMenseki  the value for skf.skf3030_t_rental_pattern.shataku_calc_menseki
	 * @mbg.generated
	 */
	public void setShatakuCalcMenseki(Short shatakuCalcMenseki) {
		this.shatakuCalcMenseki = shatakuCalcMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.aging_residual_rate
	 * @return  the value of skf.skf3030_t_rental_pattern.aging_residual_rate
	 * @mbg.generated
	 */
	public BigDecimal getAgingResidualRate() {
		return agingResidualRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.aging_residual_rate
	 * @param agingResidualRate  the value for skf.skf3030_t_rental_pattern.aging_residual_rate
	 * @mbg.generated
	 */
	public void setAgingResidualRate(BigDecimal agingResidualRate) {
		this.agingResidualRate = agingResidualRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.menseki
	 * @return  the value of skf.skf3030_t_rental_pattern.menseki
	 * @mbg.generated
	 */
	public BigDecimal getMenseki() {
		return menseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.menseki
	 * @param menseki  the value for skf.skf3030_t_rental_pattern.menseki
	 * @mbg.generated
	 */
	public void setMenseki(BigDecimal menseki) {
		this.menseki = menseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.sun_room_menseki
	 * @return  the value of skf.skf3030_t_rental_pattern.sun_room_menseki
	 * @mbg.generated
	 */
	public BigDecimal getSunRoomMenseki() {
		return sunRoomMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.sun_room_menseki
	 * @param sunRoomMenseki  the value for skf.skf3030_t_rental_pattern.sun_room_menseki
	 * @mbg.generated
	 */
	public void setSunRoomMenseki(BigDecimal sunRoomMenseki) {
		this.sunRoomMenseki = sunRoomMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.stairs_menseki
	 * @return  the value of skf.skf3030_t_rental_pattern.stairs_menseki
	 * @mbg.generated
	 */
	public BigDecimal getStairsMenseki() {
		return stairsMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.stairs_menseki
	 * @param stairsMenseki  the value for skf.skf3030_t_rental_pattern.stairs_menseki
	 * @mbg.generated
	 */
	public void setStairsMenseki(BigDecimal stairsMenseki) {
		this.stairsMenseki = stairsMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.barn_menseki
	 * @return  the value of skf.skf3030_t_rental_pattern.barn_menseki
	 * @mbg.generated
	 */
	public BigDecimal getBarnMenseki() {
		return barnMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.barn_menseki
	 * @param barnMenseki  the value for skf.skf3030_t_rental_pattern.barn_menseki
	 * @mbg.generated
	 */
	public void setBarnMenseki(BigDecimal barnMenseki) {
		this.barnMenseki = barnMenseki;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_file
	 * @return  the value of skf.skf3030_t_rental_pattern.shiryo_hosoku_file
	 * @mbg.generated
	 */
	public byte[] getShiryoHosokuFile() {
		return shiryoHosokuFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_rental_pattern.shiryo_hosoku_file
	 * @param shiryoHosokuFile  the value for skf.skf3030_t_rental_pattern.shiryo_hosoku_file
	 * @mbg.generated
	 */
	public void setShiryoHosokuFile(byte[] shiryoHosokuFile) {
		this.shiryoHosokuFile = shiryoHosokuFile;
	}
}