package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3021TNyutaikyoYoteiDataKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.shain_no
	 * @mbg.generated
	 */
	private String shainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_kbn
	 * @mbg.generated
	 */
	private String nyutaikyoKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.shain_no
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.shain_no
	 * @mbg.generated
	 */
	public String getShainNo() {
		return shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.shain_no
	 * @param shainNo  the value for skf.skf3021_t_nyutaikyo_yotei_data.shain_no
	 * @mbg.generated
	 */
	public void setShainNo(String shainNo) {
		this.shainNo = shainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_kbn
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_kbn
	 * @mbg.generated
	 */
	public String getNyutaikyoKbn() {
		return nyutaikyoKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_kbn
	 * @param nyutaikyoKbn  the value for skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_kbn
	 * @mbg.generated
	 */
	public void setNyutaikyoKbn(String nyutaikyoKbn) {
		this.nyutaikyoKbn = nyutaikyoKbn;
	}
}