package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3030TShatakuBihinRireki extends Skf3030TShatakuBihinRirekiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_bihin_rireki.bihin_lent_status_kbn
	 * @mbg.generated
	 */
	private String bihinLentStatusKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_bihin_rireki.bihin_genbutsu_gaku
	 * @mbg.generated
	 */
	private Integer bihinGenbutsuGaku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_bihin_rireki.bihin_appl_kbn
	 * @mbg.generated
	 */
	private String bihinApplKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_bihin_rireki.bihin_return_kbn
	 * @mbg.generated
	 */
	private String bihinReturnKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3030_t_shataku_bihin_rireki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_lent_status_kbn
	 * @return  the value of skf.skf3030_t_shataku_bihin_rireki.bihin_lent_status_kbn
	 * @mbg.generated
	 */
	public String getBihinLentStatusKbn() {
		return bihinLentStatusKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_lent_status_kbn
	 * @param bihinLentStatusKbn  the value for skf.skf3030_t_shataku_bihin_rireki.bihin_lent_status_kbn
	 * @mbg.generated
	 */
	public void setBihinLentStatusKbn(String bihinLentStatusKbn) {
		this.bihinLentStatusKbn = bihinLentStatusKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_genbutsu_gaku
	 * @return  the value of skf.skf3030_t_shataku_bihin_rireki.bihin_genbutsu_gaku
	 * @mbg.generated
	 */
	public Integer getBihinGenbutsuGaku() {
		return bihinGenbutsuGaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_genbutsu_gaku
	 * @param bihinGenbutsuGaku  the value for skf.skf3030_t_shataku_bihin_rireki.bihin_genbutsu_gaku
	 * @mbg.generated
	 */
	public void setBihinGenbutsuGaku(Integer bihinGenbutsuGaku) {
		this.bihinGenbutsuGaku = bihinGenbutsuGaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_appl_kbn
	 * @return  the value of skf.skf3030_t_shataku_bihin_rireki.bihin_appl_kbn
	 * @mbg.generated
	 */
	public String getBihinApplKbn() {
		return bihinApplKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_appl_kbn
	 * @param bihinApplKbn  the value for skf.skf3030_t_shataku_bihin_rireki.bihin_appl_kbn
	 * @mbg.generated
	 */
	public void setBihinApplKbn(String bihinApplKbn) {
		this.bihinApplKbn = bihinApplKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_return_kbn
	 * @return  the value of skf.skf3030_t_shataku_bihin_rireki.bihin_return_kbn
	 * @mbg.generated
	 */
	public String getBihinReturnKbn() {
		return bihinReturnKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_bihin_rireki.bihin_return_kbn
	 * @param bihinReturnKbn  the value for skf.skf3030_t_shataku_bihin_rireki.bihin_return_kbn
	 * @mbg.generated
	 */
	public void setBihinReturnKbn(String bihinReturnKbn) {
		this.bihinReturnKbn = bihinReturnKbn;
	}
}