package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3050MAgingAdjust extends Skf3050MAgingAdjustKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_aging_adjust.aging_adjust
	 * @mbg.generated
	 */
	private Short agingAdjust;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_aging_adjust.aging_adjust
	 * @return  the value of skf.skf3050_m_aging_adjust.aging_adjust
	 * @mbg.generated
	 */
	public Short getAgingAdjust() {
		return agingAdjust;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_aging_adjust.aging_adjust
	 * @param agingAdjust  the value for skf.skf3050_m_aging_adjust.aging_adjust
	 * @mbg.generated
	 */
	public void setAgingAdjust(Short agingAdjust) {
		this.agingAdjust = agingAdjust;
	}
}