package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3050MAgingAdjustKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_aging_adjust.aging_minimum
	 * @mbg.generated
	 */
	private Short agingMinimum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_aging_adjust.area_kbn
	 * @mbg.generated
	 */
	private String areaKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_aging_adjust.structure_kbn
	 * @mbg.generated
	 */
	private String structureKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_aging_adjust.menseki_minimum
	 * @mbg.generated
	 */
	private Short mensekiMinimum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_aging_adjust.aging_minimum
	 * @return  the value of skf.skf3050_m_aging_adjust.aging_minimum
	 * @mbg.generated
	 */
	public Short getAgingMinimum() {
		return agingMinimum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_aging_adjust.aging_minimum
	 * @param agingMinimum  the value for skf.skf3050_m_aging_adjust.aging_minimum
	 * @mbg.generated
	 */
	public void setAgingMinimum(Short agingMinimum) {
		this.agingMinimum = agingMinimum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_aging_adjust.area_kbn
	 * @return  the value of skf.skf3050_m_aging_adjust.area_kbn
	 * @mbg.generated
	 */
	public String getAreaKbn() {
		return areaKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_aging_adjust.area_kbn
	 * @param areaKbn  the value for skf.skf3050_m_aging_adjust.area_kbn
	 * @mbg.generated
	 */
	public void setAreaKbn(String areaKbn) {
		this.areaKbn = areaKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_aging_adjust.structure_kbn
	 * @return  the value of skf.skf3050_m_aging_adjust.structure_kbn
	 * @mbg.generated
	 */
	public String getStructureKbn() {
		return structureKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_aging_adjust.structure_kbn
	 * @param structureKbn  the value for skf.skf3050_m_aging_adjust.structure_kbn
	 * @mbg.generated
	 */
	public void setStructureKbn(String structureKbn) {
		this.structureKbn = structureKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_aging_adjust.menseki_minimum
	 * @return  the value of skf.skf3050_m_aging_adjust.menseki_minimum
	 * @mbg.generated
	 */
	public Short getMensekiMinimum() {
		return mensekiMinimum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_aging_adjust.menseki_minimum
	 * @param mensekiMinimum  the value for skf.skf3050_m_aging_adjust.menseki_minimum
	 * @mbg.generated
	 */
	public void setMensekiMinimum(Short mensekiMinimum) {
		this.mensekiMinimum = mensekiMinimum;
	}
}