package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3021TNyutaikyoYoteiData extends Skf3021TNyutaikyoYoteiDataKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.appl_kbn
	 * @mbg.generated
	 */
	private String applKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.nyukyo_yotei_date
	 * @mbg.generated
	 */
	private String nyukyoYoteiDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.taikyo_yotei_date
	 * @mbg.generated
	 */
	private String taikyoYoteiDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.ause
	 * @mbg.generated
	 */
	private String ause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_1_start_date
	 * @mbg.generated
	 */
	private String parking1StartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_2_start_date
	 * @mbg.generated
	 */
	private String parking2StartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_request_su
	 * @mbg.generated
	 */
	private Short parkingRequestSu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_status_kbn
	 * @mbg.generated
	 */
	private String nyutaikyoApplStatusKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_urge_date
	 * @mbg.generated
	 */
	private String nyutaikyoApplUrgeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.tokushu_jijo
	 * @mbg.generated
	 */
	private String tokushuJijo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.appl_no
	 * @mbg.generated
	 */
	private String applNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.sinsei_date
	 * @mbg.generated
	 */
	private String sinseiDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.teiji_create_kbn
	 * @mbg.generated
	 */
	private String teijiCreateKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.teiji_no
	 * @mbg.generated
	 */
	private Long teijiNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.data_takingin_date
	 * @mbg.generated
	 */
	private String dataTakinginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.data_issued_date
	 * @mbg.generated
	 */
	private String dataIssuedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.now_affiliation
	 * @mbg.generated
	 */
	private String nowAffiliation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3021_t_nyutaikyo_yotei_data.new_affiliation
	 * @mbg.generated
	 */
	private String newAffiliation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.name
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.name
	 * @param name  the value for skf.skf3021_t_nyutaikyo_yotei_data.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.appl_kbn
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.appl_kbn
	 * @mbg.generated
	 */
	public String getApplKbn() {
		return applKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.appl_kbn
	 * @param applKbn  the value for skf.skf3021_t_nyutaikyo_yotei_data.appl_kbn
	 * @mbg.generated
	 */
	public void setApplKbn(String applKbn) {
		this.applKbn = applKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyukyo_yotei_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.nyukyo_yotei_date
	 * @mbg.generated
	 */
	public String getNyukyoYoteiDate() {
		return nyukyoYoteiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyukyo_yotei_date
	 * @param nyukyoYoteiDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.nyukyo_yotei_date
	 * @mbg.generated
	 */
	public void setNyukyoYoteiDate(String nyukyoYoteiDate) {
		this.nyukyoYoteiDate = nyukyoYoteiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.taikyo_yotei_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.taikyo_yotei_date
	 * @mbg.generated
	 */
	public String getTaikyoYoteiDate() {
		return taikyoYoteiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.taikyo_yotei_date
	 * @param taikyoYoteiDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.taikyo_yotei_date
	 * @mbg.generated
	 */
	public void setTaikyoYoteiDate(String taikyoYoteiDate) {
		this.taikyoYoteiDate = taikyoYoteiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.ause
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.ause
	 * @mbg.generated
	 */
	public String getAuse() {
		return ause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.ause
	 * @param ause  the value for skf.skf3021_t_nyutaikyo_yotei_data.ause
	 * @mbg.generated
	 */
	public void setAuse(String ause) {
		this.ause = ause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_1_start_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.parking_1_start_date
	 * @mbg.generated
	 */
	public String getParking1StartDate() {
		return parking1StartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_1_start_date
	 * @param parking1StartDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.parking_1_start_date
	 * @mbg.generated
	 */
	public void setParking1StartDate(String parking1StartDate) {
		this.parking1StartDate = parking1StartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_2_start_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.parking_2_start_date
	 * @mbg.generated
	 */
	public String getParking2StartDate() {
		return parking2StartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_2_start_date
	 * @param parking2StartDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.parking_2_start_date
	 * @mbg.generated
	 */
	public void setParking2StartDate(String parking2StartDate) {
		this.parking2StartDate = parking2StartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_request_su
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.parking_request_su
	 * @mbg.generated
	 */
	public Short getParkingRequestSu() {
		return parkingRequestSu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.parking_request_su
	 * @param parkingRequestSu  the value for skf.skf3021_t_nyutaikyo_yotei_data.parking_request_su
	 * @mbg.generated
	 */
	public void setParkingRequestSu(Short parkingRequestSu) {
		this.parkingRequestSu = parkingRequestSu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_status_kbn
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_status_kbn
	 * @mbg.generated
	 */
	public String getNyutaikyoApplStatusKbn() {
		return nyutaikyoApplStatusKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_status_kbn
	 * @param nyutaikyoApplStatusKbn  the value for skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_status_kbn
	 * @mbg.generated
	 */
	public void setNyutaikyoApplStatusKbn(String nyutaikyoApplStatusKbn) {
		this.nyutaikyoApplStatusKbn = nyutaikyoApplStatusKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_urge_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_urge_date
	 * @mbg.generated
	 */
	public String getNyutaikyoApplUrgeDate() {
		return nyutaikyoApplUrgeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_urge_date
	 * @param nyutaikyoApplUrgeDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.nyutaikyo_appl_urge_date
	 * @mbg.generated
	 */
	public void setNyutaikyoApplUrgeDate(String nyutaikyoApplUrgeDate) {
		this.nyutaikyoApplUrgeDate = nyutaikyoApplUrgeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.tokushu_jijo
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.tokushu_jijo
	 * @mbg.generated
	 */
	public String getTokushuJijo() {
		return tokushuJijo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.tokushu_jijo
	 * @param tokushuJijo  the value for skf.skf3021_t_nyutaikyo_yotei_data.tokushu_jijo
	 * @mbg.generated
	 */
	public void setTokushuJijo(String tokushuJijo) {
		this.tokushuJijo = tokushuJijo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.appl_no
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.appl_no
	 * @mbg.generated
	 */
	public String getApplNo() {
		return applNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.appl_no
	 * @param applNo  the value for skf.skf3021_t_nyutaikyo_yotei_data.appl_no
	 * @mbg.generated
	 */
	public void setApplNo(String applNo) {
		this.applNo = applNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.sinsei_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.sinsei_date
	 * @mbg.generated
	 */
	public String getSinseiDate() {
		return sinseiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.sinsei_date
	 * @param sinseiDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.sinsei_date
	 * @mbg.generated
	 */
	public void setSinseiDate(String sinseiDate) {
		this.sinseiDate = sinseiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.teiji_create_kbn
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.teiji_create_kbn
	 * @mbg.generated
	 */
	public String getTeijiCreateKbn() {
		return teijiCreateKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.teiji_create_kbn
	 * @param teijiCreateKbn  the value for skf.skf3021_t_nyutaikyo_yotei_data.teiji_create_kbn
	 * @mbg.generated
	 */
	public void setTeijiCreateKbn(String teijiCreateKbn) {
		this.teijiCreateKbn = teijiCreateKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.teiji_no
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.teiji_no
	 * @mbg.generated
	 */
	public Long getTeijiNo() {
		return teijiNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.teiji_no
	 * @param teijiNo  the value for skf.skf3021_t_nyutaikyo_yotei_data.teiji_no
	 * @mbg.generated
	 */
	public void setTeijiNo(Long teijiNo) {
		this.teijiNo = teijiNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.data_takingin_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.data_takingin_date
	 * @mbg.generated
	 */
	public String getDataTakinginDate() {
		return dataTakinginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.data_takingin_date
	 * @param dataTakinginDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.data_takingin_date
	 * @mbg.generated
	 */
	public void setDataTakinginDate(String dataTakinginDate) {
		this.dataTakinginDate = dataTakinginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.data_issued_date
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.data_issued_date
	 * @mbg.generated
	 */
	public String getDataIssuedDate() {
		return dataIssuedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.data_issued_date
	 * @param dataIssuedDate  the value for skf.skf3021_t_nyutaikyo_yotei_data.data_issued_date
	 * @mbg.generated
	 */
	public void setDataIssuedDate(String dataIssuedDate) {
		this.dataIssuedDate = dataIssuedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.now_affiliation
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.now_affiliation
	 * @mbg.generated
	 */
	public String getNowAffiliation() {
		return nowAffiliation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.now_affiliation
	 * @param nowAffiliation  the value for skf.skf3021_t_nyutaikyo_yotei_data.now_affiliation
	 * @mbg.generated
	 */
	public void setNowAffiliation(String nowAffiliation) {
		this.nowAffiliation = nowAffiliation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.new_affiliation
	 * @return  the value of skf.skf3021_t_nyutaikyo_yotei_data.new_affiliation
	 * @mbg.generated
	 */
	public String getNewAffiliation() {
		return newAffiliation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3021_t_nyutaikyo_yotei_data.new_affiliation
	 * @param newAffiliation  the value for skf.skf3021_t_nyutaikyo_yotei_data.new_affiliation
	 * @mbg.generated
	 */
	public void setNewAffiliation(String newAffiliation) {
		this.newAffiliation = newAffiliation;
	}
}