package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3050MParkingRental extends Skf3050MParkingRentalKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_parking_rental.parking_base_rental
	 * @mbg.generated
	 */
	private Integer parkingBaseRental;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3050_m_parking_rental
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_parking_rental.parking_base_rental
	 * @return  the value of skf.skf3050_m_parking_rental.parking_base_rental
	 * @mbg.generated
	 */
	public Integer getParkingBaseRental() {
		return parkingBaseRental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_parking_rental.parking_base_rental
	 * @param parkingBaseRental  the value for skf.skf3050_m_parking_rental.parking_base_rental
	 * @mbg.generated
	 */
	public void setParkingBaseRental(Integer parkingBaseRental) {
		this.parkingBaseRental = parkingBaseRental;
	}
}