package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3010MShatakuContract extends Skf3010MShatakuContractKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.owner_no
	 * @mbg.generated
	 */
	private Long ownerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.asset_register_no
	 * @mbg.generated
	 */
	private String assetRegisterNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.contract_start_date
	 * @mbg.generated
	 */
	private String contractStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.contract_end_date
	 * @mbg.generated
	 */
	private String contractEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.rent
	 * @mbg.generated
	 */
	private Integer rent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.kyoekihi
	 * @mbg.generated
	 */
	private Integer kyoekihi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.land_rent
	 * @mbg.generated
	 */
	private Integer landRent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3010_m_shataku_contract.biko
	 * @mbg.generated
	 */
	private String biko;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3010_m_shataku_contract
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.owner_no
	 * @return  the value of skf.skf3010_m_shataku_contract.owner_no
	 * @mbg.generated
	 */
	public Long getOwnerNo() {
		return ownerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.owner_no
	 * @param ownerNo  the value for skf.skf3010_m_shataku_contract.owner_no
	 * @mbg.generated
	 */
	public void setOwnerNo(Long ownerNo) {
		this.ownerNo = ownerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.asset_register_no
	 * @return  the value of skf.skf3010_m_shataku_contract.asset_register_no
	 * @mbg.generated
	 */
	public String getAssetRegisterNo() {
		return assetRegisterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.asset_register_no
	 * @param assetRegisterNo  the value for skf.skf3010_m_shataku_contract.asset_register_no
	 * @mbg.generated
	 */
	public void setAssetRegisterNo(String assetRegisterNo) {
		this.assetRegisterNo = assetRegisterNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.contract_start_date
	 * @return  the value of skf.skf3010_m_shataku_contract.contract_start_date
	 * @mbg.generated
	 */
	public String getContractStartDate() {
		return contractStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.contract_start_date
	 * @param contractStartDate  the value for skf.skf3010_m_shataku_contract.contract_start_date
	 * @mbg.generated
	 */
	public void setContractStartDate(String contractStartDate) {
		this.contractStartDate = contractStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.contract_end_date
	 * @return  the value of skf.skf3010_m_shataku_contract.contract_end_date
	 * @mbg.generated
	 */
	public String getContractEndDate() {
		return contractEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.contract_end_date
	 * @param contractEndDate  the value for skf.skf3010_m_shataku_contract.contract_end_date
	 * @mbg.generated
	 */
	public void setContractEndDate(String contractEndDate) {
		this.contractEndDate = contractEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.rent
	 * @return  the value of skf.skf3010_m_shataku_contract.rent
	 * @mbg.generated
	 */
	public Integer getRent() {
		return rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.rent
	 * @param rent  the value for skf.skf3010_m_shataku_contract.rent
	 * @mbg.generated
	 */
	public void setRent(Integer rent) {
		this.rent = rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.kyoekihi
	 * @return  the value of skf.skf3010_m_shataku_contract.kyoekihi
	 * @mbg.generated
	 */
	public Integer getKyoekihi() {
		return kyoekihi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.kyoekihi
	 * @param kyoekihi  the value for skf.skf3010_m_shataku_contract.kyoekihi
	 * @mbg.generated
	 */
	public void setKyoekihi(Integer kyoekihi) {
		this.kyoekihi = kyoekihi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.land_rent
	 * @return  the value of skf.skf3010_m_shataku_contract.land_rent
	 * @mbg.generated
	 */
	public Integer getLandRent() {
		return landRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.land_rent
	 * @param landRent  the value for skf.skf3010_m_shataku_contract.land_rent
	 * @mbg.generated
	 */
	public void setLandRent(Integer landRent) {
		this.landRent = landRent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3010_m_shataku_contract.biko
	 * @return  the value of skf.skf3010_m_shataku_contract.biko
	 * @mbg.generated
	 */
	public String getBiko() {
		return biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3010_m_shataku_contract.biko
	 * @param biko  the value for skf.skf3010_m_shataku_contract.biko
	 * @mbg.generated
	 */
	public void setBiko(String biko) {
		this.biko = biko;
	}
}