package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3060MAgeKasankeisuKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3060_m_age_kasankeisu.ause
	 * @mbg.generated
	 */
	private String ause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3060_m_age_kasankeisu.age_minimum
	 * @mbg.generated
	 */
	private Short ageMinimum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3060_m_age_kasankeisu
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3060_m_age_kasankeisu.ause
	 * @return  the value of skf.skf3060_m_age_kasankeisu.ause
	 * @mbg.generated
	 */
	public String getAuse() {
		return ause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3060_m_age_kasankeisu.ause
	 * @param ause  the value for skf.skf3060_m_age_kasankeisu.ause
	 * @mbg.generated
	 */
	public void setAuse(String ause) {
		this.ause = ause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3060_m_age_kasankeisu.age_minimum
	 * @return  the value of skf.skf3060_m_age_kasankeisu.age_minimum
	 * @mbg.generated
	 */
	public Short getAgeMinimum() {
		return ageMinimum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3060_m_age_kasankeisu.age_minimum
	 * @param ageMinimum  the value for skf.skf3060_m_age_kasankeisu.age_minimum
	 * @mbg.generated
	 */
	public void setAgeMinimum(Short ageMinimum) {
		this.ageMinimum = ageMinimum;
	}
}