package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3030TParkingRireki extends Skf3030TParkingRirekiKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_parking_rireki.parking_kanri_no
	 * @mbg.generated
	 */
	private Long parkingKanriNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_parking_rireki.parking_start_date
	 * @mbg.generated
	 */
	private String parkingStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_parking_rireki.parking_end_date
	 * @mbg.generated
	 */
	private String parkingEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_parking_rireki.parking_kanri_no
	 * @return  the value of skf.skf3030_t_parking_rireki.parking_kanri_no
	 * @mbg.generated
	 */
	public Long getParkingKanriNo() {
		return parkingKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_parking_rireki.parking_kanri_no
	 * @param parkingKanriNo  the value for skf.skf3030_t_parking_rireki.parking_kanri_no
	 * @mbg.generated
	 */
	public void setParkingKanriNo(Long parkingKanriNo) {
		this.parkingKanriNo = parkingKanriNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_parking_rireki.parking_start_date
	 * @return  the value of skf.skf3030_t_parking_rireki.parking_start_date
	 * @mbg.generated
	 */
	public String getParkingStartDate() {
		return parkingStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_parking_rireki.parking_start_date
	 * @param parkingStartDate  the value for skf.skf3030_t_parking_rireki.parking_start_date
	 * @mbg.generated
	 */
	public void setParkingStartDate(String parkingStartDate) {
		this.parkingStartDate = parkingStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_parking_rireki.parking_end_date
	 * @return  the value of skf.skf3030_t_parking_rireki.parking_end_date
	 * @mbg.generated
	 */
	public String getParkingEndDate() {
		return parkingEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_parking_rireki.parking_end_date
	 * @param parkingEndDate  the value for skf.skf3030_t_parking_rireki.parking_end_date
	 * @mbg.generated
	 */
	public void setParkingEndDate(String parkingEndDate) {
		this.parkingEndDate = parkingEndDate;
	}
}