package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3070TOwnerInfo extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.owner_no
	 * @mbg.generated
	 */
	private Long ownerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.owner_name
	 * @mbg.generated
	 */
	private String ownerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.owner_name_kk
	 * @mbg.generated
	 */
	private String ownerNameKk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.zip_cd
	 * @mbg.generated
	 */
	private String zipCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.business_kbn
	 * @mbg.generated
	 */
	private String businessKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.accept_flg
	 * @mbg.generated
	 */
	private String acceptFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.accept_status
	 * @mbg.generated
	 */
	private String acceptStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3070_t_owner_info.remarks
	 * @mbg.generated
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3070_t_owner_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.owner_no
	 * @return  the value of skf.skf3070_t_owner_info.owner_no
	 * @mbg.generated
	 */
	public Long getOwnerNo() {
		return ownerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.owner_no
	 * @param ownerNo  the value for skf.skf3070_t_owner_info.owner_no
	 * @mbg.generated
	 */
	public void setOwnerNo(Long ownerNo) {
		this.ownerNo = ownerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.owner_name
	 * @return  the value of skf.skf3070_t_owner_info.owner_name
	 * @mbg.generated
	 */
	public String getOwnerName() {
		return ownerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.owner_name
	 * @param ownerName  the value for skf.skf3070_t_owner_info.owner_name
	 * @mbg.generated
	 */
	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.owner_name_kk
	 * @return  the value of skf.skf3070_t_owner_info.owner_name_kk
	 * @mbg.generated
	 */
	public String getOwnerNameKk() {
		return ownerNameKk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.owner_name_kk
	 * @param ownerNameKk  the value for skf.skf3070_t_owner_info.owner_name_kk
	 * @mbg.generated
	 */
	public void setOwnerNameKk(String ownerNameKk) {
		this.ownerNameKk = ownerNameKk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.zip_cd
	 * @return  the value of skf.skf3070_t_owner_info.zip_cd
	 * @mbg.generated
	 */
	public String getZipCd() {
		return zipCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.zip_cd
	 * @param zipCd  the value for skf.skf3070_t_owner_info.zip_cd
	 * @mbg.generated
	 */
	public void setZipCd(String zipCd) {
		this.zipCd = zipCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.address
	 * @return  the value of skf.skf3070_t_owner_info.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.address
	 * @param address  the value for skf.skf3070_t_owner_info.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.business_kbn
	 * @return  the value of skf.skf3070_t_owner_info.business_kbn
	 * @mbg.generated
	 */
	public String getBusinessKbn() {
		return businessKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.business_kbn
	 * @param businessKbn  the value for skf.skf3070_t_owner_info.business_kbn
	 * @mbg.generated
	 */
	public void setBusinessKbn(String businessKbn) {
		this.businessKbn = businessKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.accept_flg
	 * @return  the value of skf.skf3070_t_owner_info.accept_flg
	 * @mbg.generated
	 */
	public String getAcceptFlg() {
		return acceptFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.accept_flg
	 * @param acceptFlg  the value for skf.skf3070_t_owner_info.accept_flg
	 * @mbg.generated
	 */
	public void setAcceptFlg(String acceptFlg) {
		this.acceptFlg = acceptFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.accept_status
	 * @return  the value of skf.skf3070_t_owner_info.accept_status
	 * @mbg.generated
	 */
	public String getAcceptStatus() {
		return acceptStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.accept_status
	 * @param acceptStatus  the value for skf.skf3070_t_owner_info.accept_status
	 * @mbg.generated
	 */
	public void setAcceptStatus(String acceptStatus) {
		this.acceptStatus = acceptStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3070_t_owner_info.remarks
	 * @return  the value of skf.skf3070_t_owner_info.remarks
	 * @mbg.generated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3070_t_owner_info.remarks
	 * @param remarks  the value for skf.skf3070_t_owner_info.remarks
	 * @mbg.generated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}