package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3030TShatakuMutual extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.shataku_kanri_id
	 * @mbg.generated
	 */
	private Long shatakuKanriId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.kashituke_company_cd
	 * @mbg.generated
	 */
	private String kashitukeCompanyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.kariuke_company_cd
	 * @mbg.generated
	 */
	private String kariukeCompanyCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.rent
	 * @mbg.generated
	 */
	private Integer rent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.parking_rental
	 * @mbg.generated
	 */
	private Integer parkingRental;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.kyoekihi_business
	 * @mbg.generated
	 */
	private Integer kyoekihiBusiness;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.mutual_use_start_day
	 * @mbg.generated
	 */
	private String mutualUseStartDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.mutual_use_end_day
	 * @mbg.generated
	 */
	private String mutualUseEndDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.mutual_use_kbn
	 * @mbg.generated
	 */
	private String mutualUseKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.shataku_company_transfer_kbn
	 * @mbg.generated
	 */
	private String shatakuCompanyTransferKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.kyoekihi_company_transfer_kbn
	 * @mbg.generated
	 */
	private String kyoekihiCompanyTransferKbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3030_t_shataku_mutual.mutual_jokyo
	 * @mbg.generated
	 */
	private String mutualJokyo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3030_t_shataku_mutual
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.shataku_kanri_id
	 * @return  the value of skf.skf3030_t_shataku_mutual.shataku_kanri_id
	 * @mbg.generated
	 */
	public Long getShatakuKanriId() {
		return shatakuKanriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.shataku_kanri_id
	 * @param shatakuKanriId  the value for skf.skf3030_t_shataku_mutual.shataku_kanri_id
	 * @mbg.generated
	 */
	public void setShatakuKanriId(Long shatakuKanriId) {
		this.shatakuKanriId = shatakuKanriId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.kashituke_company_cd
	 * @return  the value of skf.skf3030_t_shataku_mutual.kashituke_company_cd
	 * @mbg.generated
	 */
	public String getKashitukeCompanyCd() {
		return kashitukeCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.kashituke_company_cd
	 * @param kashitukeCompanyCd  the value for skf.skf3030_t_shataku_mutual.kashituke_company_cd
	 * @mbg.generated
	 */
	public void setKashitukeCompanyCd(String kashitukeCompanyCd) {
		this.kashitukeCompanyCd = kashitukeCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.kariuke_company_cd
	 * @return  the value of skf.skf3030_t_shataku_mutual.kariuke_company_cd
	 * @mbg.generated
	 */
	public String getKariukeCompanyCd() {
		return kariukeCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.kariuke_company_cd
	 * @param kariukeCompanyCd  the value for skf.skf3030_t_shataku_mutual.kariuke_company_cd
	 * @mbg.generated
	 */
	public void setKariukeCompanyCd(String kariukeCompanyCd) {
		this.kariukeCompanyCd = kariukeCompanyCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.rent
	 * @return  the value of skf.skf3030_t_shataku_mutual.rent
	 * @mbg.generated
	 */
	public Integer getRent() {
		return rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.rent
	 * @param rent  the value for skf.skf3030_t_shataku_mutual.rent
	 * @mbg.generated
	 */
	public void setRent(Integer rent) {
		this.rent = rent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.parking_rental
	 * @return  the value of skf.skf3030_t_shataku_mutual.parking_rental
	 * @mbg.generated
	 */
	public Integer getParkingRental() {
		return parkingRental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.parking_rental
	 * @param parkingRental  the value for skf.skf3030_t_shataku_mutual.parking_rental
	 * @mbg.generated
	 */
	public void setParkingRental(Integer parkingRental) {
		this.parkingRental = parkingRental;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.kyoekihi_business
	 * @return  the value of skf.skf3030_t_shataku_mutual.kyoekihi_business
	 * @mbg.generated
	 */
	public Integer getKyoekihiBusiness() {
		return kyoekihiBusiness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.kyoekihi_business
	 * @param kyoekihiBusiness  the value for skf.skf3030_t_shataku_mutual.kyoekihi_business
	 * @mbg.generated
	 */
	public void setKyoekihiBusiness(Integer kyoekihiBusiness) {
		this.kyoekihiBusiness = kyoekihiBusiness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.mutual_use_start_day
	 * @return  the value of skf.skf3030_t_shataku_mutual.mutual_use_start_day
	 * @mbg.generated
	 */
	public String getMutualUseStartDay() {
		return mutualUseStartDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.mutual_use_start_day
	 * @param mutualUseStartDay  the value for skf.skf3030_t_shataku_mutual.mutual_use_start_day
	 * @mbg.generated
	 */
	public void setMutualUseStartDay(String mutualUseStartDay) {
		this.mutualUseStartDay = mutualUseStartDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.mutual_use_end_day
	 * @return  the value of skf.skf3030_t_shataku_mutual.mutual_use_end_day
	 * @mbg.generated
	 */
	public String getMutualUseEndDay() {
		return mutualUseEndDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.mutual_use_end_day
	 * @param mutualUseEndDay  the value for skf.skf3030_t_shataku_mutual.mutual_use_end_day
	 * @mbg.generated
	 */
	public void setMutualUseEndDay(String mutualUseEndDay) {
		this.mutualUseEndDay = mutualUseEndDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.mutual_use_kbn
	 * @return  the value of skf.skf3030_t_shataku_mutual.mutual_use_kbn
	 * @mbg.generated
	 */
	public String getMutualUseKbn() {
		return mutualUseKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.mutual_use_kbn
	 * @param mutualUseKbn  the value for skf.skf3030_t_shataku_mutual.mutual_use_kbn
	 * @mbg.generated
	 */
	public void setMutualUseKbn(String mutualUseKbn) {
		this.mutualUseKbn = mutualUseKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.shataku_company_transfer_kbn
	 * @return  the value of skf.skf3030_t_shataku_mutual.shataku_company_transfer_kbn
	 * @mbg.generated
	 */
	public String getShatakuCompanyTransferKbn() {
		return shatakuCompanyTransferKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.shataku_company_transfer_kbn
	 * @param shatakuCompanyTransferKbn  the value for skf.skf3030_t_shataku_mutual.shataku_company_transfer_kbn
	 * @mbg.generated
	 */
	public void setShatakuCompanyTransferKbn(String shatakuCompanyTransferKbn) {
		this.shatakuCompanyTransferKbn = shatakuCompanyTransferKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.kyoekihi_company_transfer_kbn
	 * @return  the value of skf.skf3030_t_shataku_mutual.kyoekihi_company_transfer_kbn
	 * @mbg.generated
	 */
	public String getKyoekihiCompanyTransferKbn() {
		return kyoekihiCompanyTransferKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.kyoekihi_company_transfer_kbn
	 * @param kyoekihiCompanyTransferKbn  the value for skf.skf3030_t_shataku_mutual.kyoekihi_company_transfer_kbn
	 * @mbg.generated
	 */
	public void setKyoekihiCompanyTransferKbn(String kyoekihiCompanyTransferKbn) {
		this.kyoekihiCompanyTransferKbn = kyoekihiCompanyTransferKbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3030_t_shataku_mutual.mutual_jokyo
	 * @return  the value of skf.skf3030_t_shataku_mutual.mutual_jokyo
	 * @mbg.generated
	 */
	public String getMutualJokyo() {
		return mutualJokyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3030_t_shataku_mutual.mutual_jokyo
	 * @param mutualJokyo  the value for skf.skf3030_t_shataku_mutual.mutual_jokyo
	 * @mbg.generated
	 */
	public void setMutualJokyo(String mutualJokyo) {
		this.mutualJokyo = mutualJokyo;
	}
}