package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3050MPayInKind extends Skf3050MPayInKindKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_pay_in_kind.kyoju_riekigaku
	 * @mbg.generated
	 */
	private Short kyojuRiekigaku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3050_m_pay_in_kind
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_pay_in_kind.kyoju_riekigaku
	 * @return  the value of skf.skf3050_m_pay_in_kind.kyoju_riekigaku
	 * @mbg.generated
	 */
	public Short getKyojuRiekigaku() {
		return kyojuRiekigaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_pay_in_kind.kyoju_riekigaku
	 * @param kyojuRiekigaku  the value for skf.skf3050_m_pay_in_kind.kyoju_riekigaku
	 * @mbg.generated
	 */
	public void setKyojuRiekigaku(Short kyojuRiekigaku) {
		this.kyojuRiekigaku = kyojuRiekigaku;
	}
}