package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import java.math.BigDecimal;

public class Skf3022MAgingResidualRate extends Skf3022MAgingResidualRateKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3022_m_aging_residual_rate.aging_residual_rate
	 * @mbg.generated
	 */
	private BigDecimal agingResidualRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3022_m_aging_residual_rate
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3022_m_aging_residual_rate.aging_residual_rate
	 * @return  the value of skf.skf3022_m_aging_residual_rate.aging_residual_rate
	 * @mbg.generated
	 */
	public BigDecimal getAgingResidualRate() {
		return agingResidualRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3022_m_aging_residual_rate.aging_residual_rate
	 * @param agingResidualRate  the value for skf.skf3022_m_aging_residual_rate.aging_residual_rate
	 * @mbg.generated
	 */
	public void setAgingResidualRate(BigDecimal agingResidualRate) {
		this.agingResidualRate = agingResidualRate;
	}
}