package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;

public class Skf3010MShatakuParkingWithBLOBs extends Skf3010MShatakuParking implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skf.skf3010_m_shataku_parking.parking_supplement_file_1
     *
     * @mbg.generated
     */
    private byte[] parkingSupplementFile1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skf.skf3010_m_shataku_parking.parking_supplement_file_2
     *
     * @mbg.generated
     */
    private byte[] parkingSupplementFile2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skf.skf3010_m_shataku_parking.parking_supplement_file_3
     *
     * @mbg.generated
     */
    private byte[] parkingSupplementFile3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skf.skf3010_m_shataku_parking
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skf.skf3010_m_shataku_parking.parking_supplement_file_1
     *
     * @return the value of skf.skf3010_m_shataku_parking.parking_supplement_file_1
     *
     * @mbg.generated
     */
    public byte[] getParkingSupplementFile1() {
        return parkingSupplementFile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skf.skf3010_m_shataku_parking.parking_supplement_file_1
     *
     * @param parkingSupplementFile1 the value for skf.skf3010_m_shataku_parking.parking_supplement_file_1
     *
     * @mbg.generated
     */
    public void setParkingSupplementFile1(byte[] parkingSupplementFile1) {
        this.parkingSupplementFile1 = parkingSupplementFile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skf.skf3010_m_shataku_parking.parking_supplement_file_2
     *
     * @return the value of skf.skf3010_m_shataku_parking.parking_supplement_file_2
     *
     * @mbg.generated
     */
    public byte[] getParkingSupplementFile2() {
        return parkingSupplementFile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skf.skf3010_m_shataku_parking.parking_supplement_file_2
     *
     * @param parkingSupplementFile2 the value for skf.skf3010_m_shataku_parking.parking_supplement_file_2
     *
     * @mbg.generated
     */
    public void setParkingSupplementFile2(byte[] parkingSupplementFile2) {
        this.parkingSupplementFile2 = parkingSupplementFile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skf.skf3010_m_shataku_parking.parking_supplement_file_3
     *
     * @return the value of skf.skf3010_m_shataku_parking.parking_supplement_file_3
     *
     * @mbg.generated
     */
    public byte[] getParkingSupplementFile3() {
        return parkingSupplementFile3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skf.skf3010_m_shataku_parking.parking_supplement_file_3
     *
     * @param parkingSupplementFile3 the value for skf.skf3010_m_shataku_parking.parking_supplement_file_3
     *
     * @mbg.generated
     */
    public void setParkingSupplementFile3(byte[] parkingSupplementFile3) {
        this.parkingSupplementFile3 = parkingSupplementFile3;
    }
}