package jp.co.c_nexco.businesscommon.entity.skf.table;

import java.io.Serializable;
import jp.co.c_nexco.nfw.common.entity.base.BaseEntity;

public class Skf3050MPayInKindBiko extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_pay_in_kind_biko.effective_date
	 * @mbg.generated
	 */
	private String effectiveDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf.skf3050_m_pay_in_kind_biko.biko
	 * @mbg.generated
	 */
	private String biko;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf.skf3050_m_pay_in_kind_biko
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_pay_in_kind_biko.effective_date
	 * @return  the value of skf.skf3050_m_pay_in_kind_biko.effective_date
	 * @mbg.generated
	 */
	public String getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_pay_in_kind_biko.effective_date
	 * @param effectiveDate  the value for skf.skf3050_m_pay_in_kind_biko.effective_date
	 * @mbg.generated
	 */
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf.skf3050_m_pay_in_kind_biko.biko
	 * @return  the value of skf.skf3050_m_pay_in_kind_biko.biko
	 * @mbg.generated
	 */
	public String getBiko() {
		return biko;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf.skf3050_m_pay_in_kind_biko.biko
	 * @param biko  the value for skf.skf3050_m_pay_in_kind_biko.biko
	 * @mbg.generated
	 */
	public void setBiko(String biko) {
		this.biko = biko;
	}
}