package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MAgency;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MAgencyKey;

public interface Skf1010MAgencyRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_agency
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf1010MAgencyKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_agency
	 * @mbg.generated
	 */
	int insert(Skf1010MAgency record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_agency
	 * @mbg.generated
	 */
	int insertSelective(Skf1010MAgency record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_agency
	 * @mbg.generated
	 */
	Skf1010MAgency selectByPrimaryKey(Skf1010MAgencyKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_agency
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf1010MAgency record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_agency
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf1010MAgency record);
}