package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010WSoshiki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010WSoshikiKey;

public interface Skf1010WSoshikiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_w_soshiki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf1010WSoshikiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_w_soshiki
	 * @mbg.generated
	 */
	int insert(Skf1010WSoshiki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_w_soshiki
	 * @mbg.generated
	 */
	int insertSelective(Skf1010WSoshiki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_w_soshiki
	 * @mbg.generated
	 */
	Skf1010WSoshiki selectByPrimaryKey(Skf1010WSoshikiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_w_soshiki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf1010WSoshiki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_w_soshiki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf1010WSoshiki record);
}