package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010TBatchControl;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010TBatchControlKey;

public interface Skf1010TBatchControlRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_batch_control
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf1010TBatchControlKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_batch_control
	 * @mbg.generated
	 */
	int insert(Skf1010TBatchControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_batch_control
	 * @mbg.generated
	 */
	int insertSelective(Skf1010TBatchControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_batch_control
	 * @mbg.generated
	 */
	Skf1010TBatchControl selectByPrimaryKey(Skf1010TBatchControlKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_batch_control
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf1010TBatchControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_batch_control
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf1010TBatchControl record);
}