package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MBusinessArea;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MBusinessAreaKey;

public interface Skf1010MBusinessAreaRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_business_area
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf1010MBusinessAreaKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_business_area
	 * @mbg.generated
	 */
	int insert(Skf1010MBusinessArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_business_area
	 * @mbg.generated
	 */
	int insertSelective(Skf1010MBusinessArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_business_area
	 * @mbg.generated
	 */
	Skf1010MBusinessArea selectByPrimaryKey(Skf1010MBusinessAreaKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_business_area
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf1010MBusinessArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_business_area
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf1010MBusinessArea record);
}