package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MTokyu;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MTokyuKey;

public interface Skf1010MTokyuRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_tokyu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf1010MTokyuKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_tokyu
	 * @mbg.generated
	 */
	int insert(Skf1010MTokyu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_tokyu
	 * @mbg.generated
	 */
	int insertSelective(Skf1010MTokyu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_tokyu
	 * @mbg.generated
	 */
	Skf1010MTokyu selectByPrimaryKey(Skf1010MTokyuKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_tokyu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf1010MTokyu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_tokyu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf1010MTokyu record);
}