package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MBkSoshiki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010MBkSoshikiKey;

public interface Skf1010MBkSoshikiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_bk_soshiki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf1010MBkSoshikiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_bk_soshiki
	 * @mbg.generated
	 */
	int insert(Skf1010MBkSoshiki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_bk_soshiki
	 * @mbg.generated
	 */
	int insertSelective(Skf1010MBkSoshiki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_bk_soshiki
	 * @mbg.generated
	 */
	Skf1010MBkSoshiki selectByPrimaryKey(Skf1010MBkSoshikiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_bk_soshiki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf1010MBkSoshiki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_m_bk_soshiki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf1010MBkSoshiki record);
}