package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf1010TOperationLog;

public interface Skf1010TOperationLogRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_operation_log
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long operationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_operation_log
	 * @mbg.generated
	 */
	int insert(Skf1010TOperationLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_operation_log
	 * @mbg.generated
	 */
	int insertSelective(Skf1010TOperationLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_operation_log
	 * @mbg.generated
	 */
	Skf1010TOperationLog selectByPrimaryKey(Long operationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_operation_log
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf1010TOperationLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf1010_t_operation_log
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf1010TOperationLog record);
}