package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010MApplication;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010MApplicationKey;

public interface Skf2010MApplicationRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2010MApplicationKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application
	 * @mbg.generated
	 */
	int insert(Skf2010MApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application
	 * @mbg.generated
	 */
	int insertSelective(Skf2010MApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application
	 * @mbg.generated
	 */
	Skf2010MApplication selectByPrimaryKey(Skf2010MApplicationKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2010MApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Skf2010MApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2010MApplication record);
}