package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageTeijiDetail;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageTeijiDetailKey;

public interface Skf2060TKariageTeijiDetailRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_detail
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2060TKariageTeijiDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_detail
	 * @mbg.generated
	 */
	int insert(Skf2060TKariageTeijiDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_detail
	 * @mbg.generated
	 */
	int insertSelective(Skf2060TKariageTeijiDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_detail
	 * @mbg.generated
	 */
	Skf2060TKariageTeijiDetail selectByPrimaryKey(Skf2060TKariageTeijiDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_detail
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2060TKariageTeijiDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_detail
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2060TKariageTeijiDetail record);
}