package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2050TBihinHenkyakuShinsei;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2050TBihinHenkyakuShinseiKey;

public interface Skf2050TBihinHenkyakuShinseiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2050_t_bihin_henkyaku_shinsei
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2050TBihinHenkyakuShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2050_t_bihin_henkyaku_shinsei
	 * @mbg.generated
	 */
	int insert(Skf2050TBihinHenkyakuShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2050_t_bihin_henkyaku_shinsei
	 * @mbg.generated
	 */
	int insertSelective(Skf2050TBihinHenkyakuShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2050_t_bihin_henkyaku_shinsei
	 * @mbg.generated
	 */
	Skf2050TBihinHenkyakuShinsei selectByPrimaryKey(Skf2050TBihinHenkyakuShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2050_t_bihin_henkyaku_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2050TBihinHenkyakuShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2050_t_bihin_henkyaku_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2050TBihinHenkyakuShinsei record);
}