package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2020TNyukyoChoshoTsuchi;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2020TNyukyoChoshoTsuchiKey;

public interface Skf2020TNyukyoChoshoTsuchiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2020_t_nyukyo_chosho_tsuchi
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2020TNyukyoChoshoTsuchiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2020_t_nyukyo_chosho_tsuchi
	 * @mbg.generated
	 */
	int insert(Skf2020TNyukyoChoshoTsuchi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2020_t_nyukyo_chosho_tsuchi
	 * @mbg.generated
	 */
	int insertSelective(Skf2020TNyukyoChoshoTsuchi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2020_t_nyukyo_chosho_tsuchi
	 * @mbg.generated
	 */
	Skf2020TNyukyoChoshoTsuchi selectByPrimaryKey(Skf2020TNyukyoChoshoTsuchiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2020_t_nyukyo_chosho_tsuchi
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2020TNyukyoChoshoTsuchi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2020_t_nyukyo_chosho_tsuchi
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2020TNyukyoChoshoTsuchi record);
}