package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010MWorkflow;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010MWorkflowKey;

public interface Skf2010MWorkflowRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_workflow
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2010MWorkflowKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_workflow
	 * @mbg.generated
	 */
	int insert(Skf2010MWorkflow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_workflow
	 * @mbg.generated
	 */
	int insertSelective(Skf2010MWorkflow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_workflow
	 * @mbg.generated
	 */
	Skf2010MWorkflow selectByPrimaryKey(Skf2010MWorkflowKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_workflow
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2010MWorkflow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_workflow
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2010MWorkflow record);
}