package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageTeijiFile;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageTeijiFileKey;

public interface Skf2060TKariageTeijiFileRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_file
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2060TKariageTeijiFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_file
	 * @mbg.generated
	 */
	int insert(Skf2060TKariageTeijiFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_file
	 * @mbg.generated
	 */
	int insertSelective(Skf2060TKariageTeijiFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_file
	 * @mbg.generated
	 */
	Skf2060TKariageTeijiFile selectByPrimaryKey(Skf2060TKariageTeijiFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_file
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2060TKariageTeijiFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_file
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Skf2060TKariageTeijiFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji_file
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2060TKariageTeijiFile record);
}