package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2030TBihinKiboShinsei;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2030TBihinKiboShinseiKey;

public interface Skf2030TBihinKiboShinseiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin_kibo_shinsei
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2030TBihinKiboShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin_kibo_shinsei
	 * @mbg.generated
	 */
	int insert(Skf2030TBihinKiboShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin_kibo_shinsei
	 * @mbg.generated
	 */
	int insertSelective(Skf2030TBihinKiboShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin_kibo_shinsei
	 * @mbg.generated
	 */
	Skf2030TBihinKiboShinsei selectByPrimaryKey(Skf2030TBihinKiboShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin_kibo_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2030TBihinKiboShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin_kibo_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2030TBihinKiboShinsei record);
}