package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageTeiji;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageTeijiKey;

public interface Skf2060TKariageTeijiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2060TKariageTeijiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji
	 * @mbg.generated
	 */
	int insert(Skf2060TKariageTeiji record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji
	 * @mbg.generated
	 */
	int insertSelective(Skf2060TKariageTeiji record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji
	 * @mbg.generated
	 */
	Skf2060TKariageTeiji selectByPrimaryKey(Skf2060TKariageTeijiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2060TKariageTeiji record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_teiji
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2060TKariageTeiji record);
}