package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010MApplicationCtgry;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010MApplicationCtgryKey;

public interface Skf2010MApplicationCtgryRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application_ctgry
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2010MApplicationCtgryKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application_ctgry
	 * @mbg.generated
	 */
	int insert(Skf2010MApplicationCtgry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application_ctgry
	 * @mbg.generated
	 */
	int insertSelective(Skf2010MApplicationCtgry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application_ctgry
	 * @mbg.generated
	 */
	Skf2010MApplicationCtgry selectByPrimaryKey(Skf2010MApplicationCtgryKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application_ctgry
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2010MApplicationCtgry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_m_application_ctgry
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2010MApplicationCtgry record);
}