package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2030TBihin;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2030TBihinKey;

public interface Skf2030TBihinRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2030TBihinKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin
	 * @mbg.generated
	 */
	int insert(Skf2030TBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin
	 * @mbg.generated
	 */
	int insertSelective(Skf2030TBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin
	 * @mbg.generated
	 */
	Skf2030TBihin selectByPrimaryKey(Skf2030TBihinKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2030TBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2030_t_bihin
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2030TBihin record);
}