package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterKiboShinsei;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterKiboShinseiKey;

public interface Skf2100TMobileRouterKiboShinseiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_kibo_shinsei
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2100TMobileRouterKiboShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_kibo_shinsei
	 * @mbg.generated
	 */
	int insert(Skf2100TMobileRouterKiboShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_kibo_shinsei
	 * @mbg.generated
	 */
	int insertSelective(Skf2100TMobileRouterKiboShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_kibo_shinsei
	 * @mbg.generated
	 */
	Skf2100TMobileRouterKiboShinsei selectByPrimaryKey(Skf2100TMobileRouterKiboShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_kibo_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2100TMobileRouterKiboShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_kibo_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2100TMobileRouterKiboShinsei record);
}