package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterRentalRirekiMeisai;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterRentalRirekiMeisaiKey;

public interface Skf2100TMobileRouterRentalRirekiMeisaiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki_meisai
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2100TMobileRouterRentalRirekiMeisaiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki_meisai
	 * @mbg.generated
	 */
	int insert(Skf2100TMobileRouterRentalRirekiMeisai record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki_meisai
	 * @mbg.generated
	 */
	int insertSelective(Skf2100TMobileRouterRentalRirekiMeisai record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki_meisai
	 * @mbg.generated
	 */
	Skf2100TMobileRouterRentalRirekiMeisai selectByPrimaryKey(Skf2100TMobileRouterRentalRirekiMeisaiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki_meisai
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2100TMobileRouterRentalRirekiMeisai record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki_meisai
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2100TMobileRouterRentalRirekiMeisai record);
}