package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2040TTaikyoReport;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2040TTaikyoReportKey;

public interface Skf2040TTaikyoReportRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2040_t_taikyo_report
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2040TTaikyoReportKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2040_t_taikyo_report
	 * @mbg.generated
	 */
	int insert(Skf2040TTaikyoReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2040_t_taikyo_report
	 * @mbg.generated
	 */
	int insertSelective(Skf2040TTaikyoReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2040_t_taikyo_report
	 * @mbg.generated
	 */
	Skf2040TTaikyoReport selectByPrimaryKey(Skf2040TTaikyoReportKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2040_t_taikyo_report
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2040TTaikyoReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2040_t_taikyo_report
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2040TTaikyoReport record);
}