package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterHenkyakuShinsei;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterHenkyakuShinseiKey;

public interface Skf2100TMobileRouterHenkyakuShinseiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_henkyaku_shinsei
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2100TMobileRouterHenkyakuShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_henkyaku_shinsei
	 * @mbg.generated
	 */
	int insert(Skf2100TMobileRouterHenkyakuShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_henkyaku_shinsei
	 * @mbg.generated
	 */
	int insertSelective(Skf2100TMobileRouterHenkyakuShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_henkyaku_shinsei
	 * @mbg.generated
	 */
	Skf2100TMobileRouterHenkyakuShinsei selectByPrimaryKey(Skf2100TMobileRouterHenkyakuShinseiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_henkyaku_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2100TMobileRouterHenkyakuShinsei record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_henkyaku_shinsei
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2100TMobileRouterHenkyakuShinsei record);
}