package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageBukkenFile;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2060TKariageBukkenFileKey;

public interface Skf2060TKariageBukkenFileRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2060TKariageBukkenFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	int insert(Skf2060TKariageBukkenFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	int insertSelective(Skf2060TKariageBukkenFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	Skf2060TKariageBukkenFile selectByPrimaryKey(Skf2060TKariageBukkenFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2060TKariageBukkenFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Skf2060TKariageBukkenFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2060_t_kariage_bukken_file
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2060TKariageBukkenFile record);
}