package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010TAttachedFile;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2010TAttachedFileKey;

public interface Skf2010TAttachedFileRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_t_attached_file
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2010TAttachedFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_t_attached_file
	 * @mbg.generated
	 */
	int insert(Skf2010TAttachedFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_t_attached_file
	 * @mbg.generated
	 */
	int insertSelective(Skf2010TAttachedFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_t_attached_file
	 * @mbg.generated
	 */
	Skf2010TAttachedFile selectByPrimaryKey(Skf2010TAttachedFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_t_attached_file
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2010TAttachedFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_t_attached_file
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Skf2010TAttachedFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2010_t_attached_file
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2010TAttachedFile record);
}