package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterRentalRireki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf2100TMobileRouterRentalRirekiKey;

public interface Skf2100TMobileRouterRentalRirekiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf2100TMobileRouterRentalRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki
	 * @mbg.generated
	 */
	int insert(Skf2100TMobileRouterRentalRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki
	 * @mbg.generated
	 */
	int insertSelective(Skf2100TMobileRouterRentalRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki
	 * @mbg.generated
	 */
	Skf2100TMobileRouterRentalRireki selectByPrimaryKey(Skf2100TMobileRouterRentalRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf2100TMobileRouterRentalRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf2100_t_mobile_router_rental_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf2100TMobileRouterRentalRireki record);
}