package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuContract;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuContractKey;

public interface Skf3010MShatakuContractRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_contract
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3010MShatakuContractKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_contract
	 * @mbg.generated
	 */
	int insert(Skf3010MShatakuContract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_contract
	 * @mbg.generated
	 */
	int insertSelective(Skf3010MShatakuContract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_contract
	 * @mbg.generated
	 */
	Skf3010MShatakuContract selectByPrimaryKey(Skf3010MShatakuContractKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_contract
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3010MShatakuContract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_contract
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3010MShatakuContract record);
}