package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3022TShatakuYoyakuData;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3022TShatakuYoyakuDataKey;

public interface Skf3022TShatakuYoyakuDataRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_shataku_yoyaku_data
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3022TShatakuYoyakuDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_shataku_yoyaku_data
	 * @mbg.generated
	 */
	int insert(Skf3022TShatakuYoyakuData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_shataku_yoyaku_data
	 * @mbg.generated
	 */
	int insertSelective(Skf3022TShatakuYoyakuData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_shataku_yoyaku_data
	 * @mbg.generated
	 */
	Skf3022TShatakuYoyakuData selectByPrimaryKey(Skf3022TShatakuYoyakuDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_shataku_yoyaku_data
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3022TShatakuYoyakuData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_shataku_yoyaku_data
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3022TShatakuYoyakuData record);
}