package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3022MAriaHoseiritsu;

public interface Skf3022MAriaHoseiritsuRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_aria_hoseiritsu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String areaKbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_aria_hoseiritsu
	 * @mbg.generated
	 */
	int insert(Skf3022MAriaHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_aria_hoseiritsu
	 * @mbg.generated
	 */
	int insertSelective(Skf3022MAriaHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_aria_hoseiritsu
	 * @mbg.generated
	 */
	Skf3022MAriaHoseiritsu selectByPrimaryKey(String areaKbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_aria_hoseiritsu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3022MAriaHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_aria_hoseiritsu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3022MAriaHoseiritsu record);
}