package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MAgingAdjust;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MAgingAdjustKey;

public interface Skf3050MAgingAdjustRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3050MAgingAdjustKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	int insert(Skf3050MAgingAdjust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	int insertSelective(Skf3050MAgingAdjust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	Skf3050MAgingAdjust selectByPrimaryKey(Skf3050MAgingAdjustKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3050MAgingAdjust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_aging_adjust
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3050MAgingAdjust record);
}