package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MRentalBase;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MRentalBaseKey;

public interface Skf3050MRentalBaseRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_rental_base
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3050MRentalBaseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_rental_base
	 * @mbg.generated
	 */
	int insert(Skf3050MRentalBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_rental_base
	 * @mbg.generated
	 */
	int insertSelective(Skf3050MRentalBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_rental_base
	 * @mbg.generated
	 */
	Skf3050MRentalBase selectByPrimaryKey(Skf3050MRentalBaseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_rental_base
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3050MRentalBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_rental_base
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3050MRentalBase record);
}