package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3022MMensekiHoseiritsu;

public interface Skf3022MMensekiHoseiritsuRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_menseki_hoseiritsu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Short mensekiMinimum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_menseki_hoseiritsu
	 * @mbg.generated
	 */
	int insert(Skf3022MMensekiHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_menseki_hoseiritsu
	 * @mbg.generated
	 */
	int insertSelective(Skf3022MMensekiHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_menseki_hoseiritsu
	 * @mbg.generated
	 */
	Skf3022MMensekiHoseiritsu selectByPrimaryKey(Short mensekiMinimum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_menseki_hoseiritsu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3022MMensekiHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_menseki_hoseiritsu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3022MMensekiHoseiritsu record);
}