package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShatakuBihinRireki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShatakuBihinRirekiKey;

public interface Skf3030TShatakuBihinRirekiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin_rireki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3030TShatakuBihinRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin_rireki
	 * @mbg.generated
	 */
	int insert(Skf3030TShatakuBihinRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin_rireki
	 * @mbg.generated
	 */
	int insertSelective(Skf3030TShatakuBihinRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin_rireki
	 * @mbg.generated
	 */
	Skf3030TShatakuBihinRireki selectByPrimaryKey(Skf3030TShatakuBihinRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3030TShatakuBihinRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3030TShatakuBihinRireki record);
}