package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuParking;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuParkingWithBLOBs;

public interface Skf3010MShatakuParkingRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long shatakuKanriNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking
	 * @mbg.generated
	 */
	int insert(Skf3010MShatakuParkingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking
	 * @mbg.generated
	 */
	int insertSelective(Skf3010MShatakuParkingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking
	 * @mbg.generated
	 */
	Skf3010MShatakuParkingWithBLOBs selectByPrimaryKey(Long shatakuKanriNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3010MShatakuParkingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Skf3010MShatakuParkingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3010MShatakuParking record);
}