package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3022MStructureHoseiritsu;

public interface Skf3022MStructureHoseiritsuRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_structure_hoseiritsu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String structureKbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_structure_hoseiritsu
	 * @mbg.generated
	 */
	int insert(Skf3022MStructureHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_structure_hoseiritsu
	 * @mbg.generated
	 */
	int insertSelective(Skf3022MStructureHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_structure_hoseiritsu
	 * @mbg.generated
	 */
	Skf3022MStructureHoseiritsu selectByPrimaryKey(String structureKbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_structure_hoseiritsu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3022MStructureHoseiritsu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_m_structure_hoseiritsu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3022MStructureHoseiritsu record);
}