package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3021TNyutaikyoYoteiData;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3021TNyutaikyoYoteiDataKey;

public interface Skf3021TNyutaikyoYoteiDataRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3021TNyutaikyoYoteiDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	int insert(Skf3021TNyutaikyoYoteiData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	int insertSelective(Skf3021TNyutaikyoYoteiData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	Skf3021TNyutaikyoYoteiData selectByPrimaryKey(Skf3021TNyutaikyoYoteiDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3021TNyutaikyoYoteiData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3021_t_nyutaikyo_yotei_data
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3021TNyutaikyoYoteiData record);
}