package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3022TTeijiData;

public interface Skf3022TTeijiDataRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_teiji_data
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long teijiNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_teiji_data
	 * @mbg.generated
	 */
	int insert(Skf3022TTeijiData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_teiji_data
	 * @mbg.generated
	 */
	int insertSelective(Skf3022TTeijiData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_teiji_data
	 * @mbg.generated
	 */
	Skf3022TTeijiData selectByPrimaryKey(Long teijiNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_teiji_data
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3022TTeijiData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3022_t_teiji_data
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3022TTeijiData record);
}