package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MGeneralEquipmentItem;

public interface Skf3050MGeneralEquipmentItemRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_general_equipment_item
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String generalEquipmentCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_general_equipment_item
	 * @mbg.generated
	 */
	int insert(Skf3050MGeneralEquipmentItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_general_equipment_item
	 * @mbg.generated
	 */
	int insertSelective(Skf3050MGeneralEquipmentItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_general_equipment_item
	 * @mbg.generated
	 */
	Skf3050MGeneralEquipmentItem selectByPrimaryKey(String generalEquipmentCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_general_equipment_item
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3050MGeneralEquipmentItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_general_equipment_item
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3050MGeneralEquipmentItem record);
}