package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MPayInKind;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MPayInKindKey;

public interface Skf3050MPayInKindRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_pay_in_kind
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3050MPayInKindKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_pay_in_kind
	 * @mbg.generated
	 */
	int insert(Skf3050MPayInKind record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_pay_in_kind
	 * @mbg.generated
	 */
	int insertSelective(Skf3050MPayInKind record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_pay_in_kind
	 * @mbg.generated
	 */
	Skf3050MPayInKind selectByPrimaryKey(Skf3050MPayInKindKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_pay_in_kind
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3050MPayInKind record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_pay_in_kind
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3050MPayInKind record);
}