package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuParkingBlock;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuParkingBlockKey;

public interface Skf3010MShatakuParkingBlockRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking_block
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3010MShatakuParkingBlockKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking_block
	 * @mbg.generated
	 */
	int insert(Skf3010MShatakuParkingBlock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking_block
	 * @mbg.generated
	 */
	int insertSelective(Skf3010MShatakuParkingBlock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking_block
	 * @mbg.generated
	 */
	Skf3010MShatakuParkingBlock selectByPrimaryKey(Skf3010MShatakuParkingBlockKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking_block
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3010MShatakuParkingBlock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_parking_block
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3010MShatakuParkingBlock record);
}