package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3050MBihinItem;

public interface Skf3050MBihinItemRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_bihin_item
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String bihinCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_bihin_item
	 * @mbg.generated
	 */
	int insert(Skf3050MBihinItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_bihin_item
	 * @mbg.generated
	 */
	int insertSelective(Skf3050MBihinItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_bihin_item
	 * @mbg.generated
	 */
	Skf3050MBihinItem selectByPrimaryKey(String bihinCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_bihin_item
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3050MBihinItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3050_m_bihin_item
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3050MBihinItem record);
}