package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShozokuRireki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShozokuRirekiKey;

public interface Skf3030TShozokuRirekiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shozoku_rireki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3030TShozokuRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shozoku_rireki
	 * @mbg.generated
	 */
	int insert(Skf3030TShozokuRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shozoku_rireki
	 * @mbg.generated
	 */
	int insertSelective(Skf3030TShozokuRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shozoku_rireki
	 * @mbg.generated
	 */
	Skf3030TShozokuRireki selectByPrimaryKey(Skf3030TShozokuRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shozoku_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3030TShozokuRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shozoku_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3030TShozokuRireki record);
}