package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuRoomBihin;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuRoomBihinKey;

public interface Skf3010MShatakuRoomBihinRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_room_bihin
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3010MShatakuRoomBihinKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_room_bihin
	 * @mbg.generated
	 */
	int insert(Skf3010MShatakuRoomBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_room_bihin
	 * @mbg.generated
	 */
	int insertSelective(Skf3010MShatakuRoomBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_room_bihin
	 * @mbg.generated
	 */
	Skf3010MShatakuRoomBihin selectByPrimaryKey(Skf3010MShatakuRoomBihinKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_room_bihin
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3010MShatakuRoomBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku_room_bihin
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3010MShatakuRoomBihin record);
}