package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShatakuRentalRireki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShatakuRentalRirekiKey;

public interface Skf3030TShatakuRentalRirekiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_rental_rireki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3030TShatakuRentalRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_rental_rireki
	 * @mbg.generated
	 */
	int insert(Skf3030TShatakuRentalRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_rental_rireki
	 * @mbg.generated
	 */
	int insertSelective(Skf3030TShatakuRentalRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_rental_rireki
	 * @mbg.generated
	 */
	Skf3030TShatakuRentalRireki selectByPrimaryKey(Skf3030TShatakuRentalRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_rental_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3030TShatakuRentalRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_rental_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3030TShatakuRentalRireki record);
}