package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShatakuBihin;

public interface Skf3030TShatakuBihinRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long shatakuKanriId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin
	 * @mbg.generated
	 */
	int insert(Skf3030TShatakuBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin
	 * @mbg.generated
	 */
	int insertSelective(Skf3030TShatakuBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin
	 * @mbg.generated
	 */
	Skf3030TShatakuBihin selectByPrimaryKey(Long shatakuKanriId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3030TShatakuBihin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_bihin
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3030TShatakuBihin record);
}