package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3060MAgeKasankeisu;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3060MAgeKasankeisuKey;

public interface Skf3060MAgeKasanKeisuRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_m_age_kasankeisu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3060MAgeKasankeisuKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_m_age_kasankeisu
	 * @mbg.generated
	 */
	int insert(Skf3060MAgeKasankeisu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_m_age_kasankeisu
	 * @mbg.generated
	 */
	int insertSelective(Skf3060MAgeKasankeisu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_m_age_kasankeisu
	 * @mbg.generated
	 */
	Skf3060MAgeKasankeisu selectByPrimaryKey(Skf3060MAgeKasankeisuKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_m_age_kasankeisu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3060MAgeKasankeisu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_m_age_kasankeisu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3060MAgeKasankeisu record);
}