package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShataku;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3010MShatakuWithBLOBs;

public interface Skf3010MShatakuRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long shatakuKanriNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku
	 * @mbg.generated
	 */
	int insert(Skf3010MShatakuWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku
	 * @mbg.generated
	 */
	int insertSelective(Skf3010MShatakuWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku
	 * @mbg.generated
	 */
	Skf3010MShatakuWithBLOBs selectByPrimaryKey(Long shatakuKanriNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3010MShatakuWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Skf3010MShatakuWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3010_m_shataku
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3010MShataku record);
}