package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3060TAgeKasanSendmail;

public interface Skf3060TAgeKasanSendmailRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_t_age_kasan_sendmail
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String shainNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_t_age_kasan_sendmail
	 * @mbg.generated
	 */
	int insert(Skf3060TAgeKasanSendmail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_t_age_kasan_sendmail
	 * @mbg.generated
	 */
	int insertSelective(Skf3060TAgeKasanSendmail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_t_age_kasan_sendmail
	 * @mbg.generated
	 */
	Skf3060TAgeKasanSendmail selectByPrimaryKey(String shainNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_t_age_kasan_sendmail
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3060TAgeKasanSendmail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3060_t_age_kasan_sendmail
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3060TAgeKasanSendmail record);
}