package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TParkingRireki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TParkingRirekiKey;

public interface Skf3030TParkingRirekiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3030TParkingRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	int insert(Skf3030TParkingRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	int insertSelective(Skf3030TParkingRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	Skf3030TParkingRireki selectByPrimaryKey(Skf3030TParkingRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3030TParkingRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_parking_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3030TParkingRireki record);
}