package jp.co.c_nexco.businesscommon.repository.skf.table;

import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShatakuMutualRireki;
import jp.co.c_nexco.businesscommon.entity.skf.table.Skf3030TShatakuMutualRirekiKey;

public interface Skf3030TShatakuMutualRirekiRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_mutual_rireki
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Skf3030TShatakuMutualRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_mutual_rireki
	 * @mbg.generated
	 */
	int insert(Skf3030TShatakuMutualRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_mutual_rireki
	 * @mbg.generated
	 */
	int insertSelective(Skf3030TShatakuMutualRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_mutual_rireki
	 * @mbg.generated
	 */
	Skf3030TShatakuMutualRireki selectByPrimaryKey(Skf3030TShatakuMutualRirekiKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_mutual_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Skf3030TShatakuMutualRireki record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf.skf3030_t_shataku_mutual_rireki
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Skf3030TShatakuMutualRireki record);
}